### ISSUE TITLE
Hotkeys for Mac (again :-)

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#10]
Can you add hotkeys for mac ?

normally for mac user:
cut it's cmd+x 
copy it's cmd+c
paste it's cmd+v

have you plan to implement undo , redo ?
undo: windows : ctrl+z / mac: cmd+z
redo: windows : ctrl+shift+z or ctrl+y / mac: cmd+shift+z or cmd+y

**Comment by nesbox** [comment]
will fix ctrl <-> cmd button on mac
undo/redo already implemented but with only CTRL button

**Comment by Gi972** [comment]
sure for ctrl+z and ctrl=y on mac version?
because it's doesn't  work for me.

I have a AZERTY keyboard

**Comment by nesbox** [comment]
hmm, CTRL+z/y works on my virtual machine
in Code Editor and Sprite Editor
needs investigation...

**Comment by Gi972** [comment]
I test the others Hotkeys, all I'ts ok except ctrl+z and ctrl+y.

I can't test ctrl+~  because ~ is alt+n for us. but I think its works for others keyboards versions

**Comment by nesbox** [comment]
I added CMD button support. Could you pls test it?
https://1drv.ms/u/s!AlYcILUh3RFajMFesAOTcLJZl15q9Q
Thanks

**Comment by Gi972** [comment]
Hi,

I test Cmd button it works with cmd+c, cmd+v ;-)

Undo Redo with cmd or ctrl doesn't work :-(

**Comment by nesbox** [comment]
Made another fix for ctrl+c/v
Please check it
https://1drv.ms/u/s!AlYcILUh3RFajMFfgO4DM1qU2cwjmQ

**Comment by Gi972** [comment]
no always not :/

**Comment by nesbox** [comment]
And last one https://1drv.ms/u/s!AlYcILUh3RFajMFgP9a90DNYO7aHcA
Don't have ideas anymore :(

**Comment by Gi972** [comment]
Unfortunately it doesn't work :-(

maybe your virtual machine distorts the results...

**Comment by Gi972** [comment]
Could you just fo test put two buttons on the interface one for undo, one for redo to see if the cause is the hotkey or the system?

**Comment by nesbox** [comment]
Added test undo/redo buttons to the toolbar https://1drv.ms/u/s!AlYcILUh3RFajMFhc_5YKkBPwSWAjQ

<img src="http://imgur.com/download/ArOxMy4">

**Comment by Gi972** [comment]
Hi,
It works very well with undo redo buttons
mmm...

**Comment by Gi972** [comment]
maybe try test with a other combinaison hotkeys? I know isn't the best but just to try help you found the  bug

**Comment by nesbox** [comment]
I created a test screen, just hold cmd+z/y buttons and tells me what codes do you see.
https://1drv.ms/u/s!AlYcILUh3RFajMFisTJBCCFcq4c0fw

**Comment by Gi972** [comment]
I see ctrl: 224, z: 26 , y:28, cmd:227

**Comment by nesbox** [comment]
When you press CMD+Z do you see both codes (227,26) at the same time or something else?

**Comment by Gi972** [comment]
this is a screenshot,

when I press cmd+z

<img width="769" alt="debugtic" src="https://cloud.githubusercontent.com/assets/1606247/22280398/b658904c-e2d0-11e6-8be6-b2cf64022eb0.png">

**Comment by nesbox** [comment]
Please try this https://1drv.ms/u/s!AlYcILUh3RFajMFp85SbNl1N8X2rOg

**Comment by Gi972** [comment]
So I test,

it doesn't work.
On the other hand, I have a bizarre behavior. if I use the undo button on the editor and make cmd+Y the redo function works but only the redo .

**Comment by nesbox** [comment]
ok, what is going on if you press cmd+w instead cmd+z?

**Comment by Gi972** [comment]
It works with CMD + W !!!!!!  :-D

**Comment by Gi972** [comment]
Hum!  undo works with CMD + W :-)

**Comment by nesbox** [comment]
gotcha :) will make a test soon

**Comment by nesbox** [comment]
a test should work with AZERTY keyboard
https://1drv.ms/u/s!AlYcILUh3RFajMFqNczY9Z5mSn0N8w

**Comment by Gi972** [comment]
Great !!!! It works!!

Now you need to handle the others cultures/localisation of keyboard.

But we see the end of tunnel. 

You can close this issue  ;-)

**Comment by nesbox** [comment]
fixed
