### ISSUE TITLE
VsCode Extension

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#101]
Hello @nesbox ,

I made a VsCode editor extension for tic80 
[Tic80-Vscode](https://marketplace.visualstudio.com/items?itemName=Gi972.tic80-vscode)

If you are disagree let me know and I will retire this extension.

Thanks

**Comment by harraps** [comment]
does it also work for moonscript ?

**Comment by Gi972** [comment]
I don't know,

I don't test it, but the moonscript  extension is .lua?

**Comment by nesbox** [comment]
@Gi972 are you kidding? this is great extension 😃
I twitted about it https://twitter.com/tic_computer/status/853377910320898048
Thank you

**Comment by trelemar** [comment]
Huh, I went to go assign a tag for this the exact moment @nesbox closed this issue which caused it to re-open. In any case, great job! May have to give vscode a try tonight!

**Comment by nesbox** [comment]
Also added info about extension to the Wiki https://github.com/nesbox/tic.computer/wiki#using-external-code-editors

**Comment by Gi972** [comment]
Ok,
I will improve soon , make test with windows and moonlight.

**Comment by harraps** [comment]
moonscript extension is .moon
but if it is only a matter of extension, it should be quickly fixed.

**Comment by nesbox** [comment]
I think you have to install extension https://marketplace.visualstudio.com/items?itemName=simonkaae.moonscript to add Moonscript support to the VSCode

**Comment by Gi972** [comment]
I try, it's works with moon file.
and effectively install moonscript extension
