### ISSUE TITLE
Sprite editor - Selection tool bug

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#102]
- **Description:** 
  - After selecting an area, moving selection, deselecting, reselecting and moving the selection, the original | first position of the selection is erased.
- **Record:**
![selectiontoolbug](https://cloud.githubusercontent.com/assets/17261132/25072243/d4d82b66-22c9-11e7-96b9-ced7301c9156.gif)

**Comment by nesbox** [comment]
fixed on .23
