### ISSUE TITLE
Palette swapping function

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#104]
Just like PICO-8's `pal(c0,c1,[p])` function.
An enhancement might be to have a table with same lengths for both `c0` and `c1` to change multiple colors at once.
TIC-80's `font` function might be removed from TIC-80 because:
```Lua
function myFont(text,x,y,color,spacing,startIndex)
	for i=1,#text do
		pal(15,color)
		spr(startIndex+(string.byte(text,i)-32),x+((i-1)*spacing),y,0)
		pal()
	end
end
```

**Comment by nesbox** [comment]
You could write your own `pal` function as you wrote for the `myFont`
Use `poke` by `3FF0-PALETTE MAP` addr
btw, current `font` api can render non-fixed width font

**Comment by AnastasiaDunbar** [comment]
@nesbox Like this?
```Lua
function myFont(text,x,y,color,spacing,startIndex)
	for i=1,#text do
		poke(16368+7,14+(color*16))
		spr(startIndex+(string.byte(text,i)-32),x+((i-1)*spacing),y,0)
		poke(16368+7,254)
	end
end
```

**Comment by nesbox** [comment]
PALETTE MAP is array of color indexes and it equals `[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]` by default
``` lua
function pal(c0,c1)
 poke(0x3FF0+c0, c1) -- remap c0 color with c1
 -- draw your stuff ...
 poke(0x3FF0+c0, c0) -- restore palette map
end
```

**Comment by AnastasiaDunbar** [comment]
@nesbox
Array? I got number values instead so I wrote this:
```Lua
--[[
 IDs  Address A   B      Value
 0, 1 16368  : 0+( 1*16)=16
 2, 3 16369  : 2+( 3*16)=50
 4, 5 16370  : 4+( 5*16)=84
 6, 7 16371  : 6+( 7*16)=118
 8, 9 16372  : 8+( 9*16)=152
10,11 16373  :10+(11*16)=186
12,13 16374  :12+(13*16)=220
14,15 16375  :14+(15*16)=254
Solve for B in Value where A is from 0 to 15:
	floor(Value/16)
Solve for A in Value:
	Value-(floor(Value/16)*16)
--]]
function pal(c0,c1)
	if(c0==nil and c1==nil)then
		for i=0,7 do
			poke(16368+i,(i*2)+(((i*2)+1)*16))
		end
	else
		c0=math.floor(c0)%16
		c1=math.floor(c1)%16
		local addr=16368+math.floor(c0/2)
		local val=peek(addr)
		local b=math.floor(peek(addr)/16)
		local a=val-(b*16)
		if(c0%2==0)then
			poke(addr,c0+(b*16))
		else
			poke(addr,a+(c0*16))
		end
	end
end
```

**Comment by nesbox** [comment]
ups, my mistake, it's array of 4bit values, pls use `poke4` instead
``` lua
function pal(c0,c1)
 if(c0==nil and c1==nil)then for i=0,15 do poke4(0x3FF0*2+i,i)end
 else poke4(0x3FF0*2+c0,c1) end
end
```
sorry

**Comment by AnastasiaDunbar** [comment]
Oh, that's why poke4 exists?

**Comment by nesbox** [comment]
in particular, here is set_pixel for example
``` lua
function set_pixel (x,y,c) poke4(0x0000+x+y*240,c) end
```

**Comment by nesbox** [comment]
added **Palette swapping** to Wiki https://github.com/nesbox/tic.computer/wiki/Code-examples-and-snippets#palette-swapping
I think we can close the issue...

**Comment by adrienhub** [comment]
> oops, my mistake, it's array of 4bit values, pls use `poke4` instead
> 
> ```lua
> function pal(c0,c1)
>  if(c0==nil and c1==nil)then for i=0,15 do poke4(0x3FF0*2+i,i)end
>  else poke4(0x3FF0*2+c0,c1) end
> end
> ```
> 
> sorry

Thats so cool, can we have example of it, what is color c0, c1 values and how to retrieve them from the palette please?

**Comment by adrienhub** [comment]
> > oops, my mistake, it's array of 4bit values, pls use `poke4` instead
> > ```lua
> > function pal(c0,c1)
> >  if(c0==nil and c1==nil)then for i=0,15 do poke4(0x3FF0*2+i,i)end
> >  else poke4(0x3FF0*2+c0,c1) end
> > end
> > ```
> > 
> > 
> > sorry
> 
> Thats so cool, can we have example of it, what is color c0, c1 values and how to retrieve them from the palette please?

hmm hex values right?

**Comment by adrienhub** [comment]
> > > oops, my mistake, it's array of 4bit values, pls use `poke4` instead
> > > ```lua
> > > function pal(c0,c1)
> > >  if(c0==nil and c1==nil)then for i=0,15 do poke4(0x3FF0*2+i,i)end
> > >  else poke4(0x3FF0*2+c0,c1) end
> > > end
> > > ```
> > > 
> > > 
> > > sorry
> > 
> > 
> > Thats so cool, can we have example of it, what is color c0, c1 values and how to retrieve them from the palette please?
> 
> hmm hex values right?

sorry I didn't understood, its not a entire palette swap only colors index existing on the palette, my bad! thanks for the great work! <3
