### ISSUE TITLE
Cheatsheet for TIC-80

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#107]
Here's one I've made so far (_upscale by 2x with nearest-neighbor interpolation_):
![tic-80 cheatsheet](https://cloud.githubusercontent.com/assets/11806048/25425994/5ad03262-2aa0-11e7-87d3-1fae398f7f8a.png)
I thank @nesbox for helping me out with some functions.
I'd kinda like to see the community make one too.

**Comment by AlRado** [comment]
Cool!
It seems to me it is possible to make the text more readable - to change a font, for example on this http://www.pentacom.jp/pentacom/bitfontmaker2/gallery/?id=468 Or another, slightly larger

**Comment by trelemar** [comment]
Very neat! I noticed your dpad buttons are all facing the wrong way, useful nonetheless!

**Comment by AnastasiaDunbar** [comment]
@trelemar Fixed it.

**Comment by trelemar** [comment]
This sheet is useful, but not an actual Issue. Also is a bit dated by now. We can probably put an updated one on the wiki at some point. Closing for clean up.

**Comment by Effer** [comment]
Cheatsheet will be really a nice addiction. Hope @AnastasiaDunbar or some skilled guy will draw one. Even if some sort of offline help (like the one in qbasic) will fit perfectly in TIC. 
It was suggested somewhere to have an offline help, isn't it?
