### ISSUE TITLE
Map same keys for SFX and MUSIC Editor

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#112]
It would be nice to have the same note/key layout, to simplify testing melodies.

**Comment by trelemar** [comment]
I've actually thought about opening an issue for this as well. It'd be nice to preview the notes while in the sfx editor. We could creat melodies like an actual keyboard, then worry about mapping/tracking it after.

**Comment by nesbox** [comment]
![piano](https://cloud.githubusercontent.com/assets/1101448/25651319/1f7693e6-2feb-11e7-8827-031f0994e1c3.png)

done on .23
closing

**Comment by trelemar** [comment]
Not working on linux 64 bit.

**Comment by nesbox** [comment]
@trelemar #114
