### ISSUE TITLE
Sprite editor: copy > scale > paste bug

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#115]
- **Description:**
A little funny bug appears when changing the scale of sprite selection in sprite editor between copying and pasting. In earlier versions was not possible to paste sprite after changing a scale. Now it pastes wird patterns. 
- **Record:**
![spriteeditorcopypastebug](https://cloud.githubusercontent.com/assets/17261132/25722157/5d3270aa-3113-11e7-95e8-43b9eb5567cf.gif)
- **Idea:** 
It will maybe useless but it could paste scaled sprite instead of nothing or this wird patterns 😄

**Comment by nesbox** [comment]
fixed on .24 (without scaling 😄 )
