### ISSUE TITLE
Mouse cursor

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#116]
I think it'd be pretty cool if tic had an emulated mouse cusor. An 8*8 sprite you could modify in the config.

**Comment by nesbox** [comment]
I remember discussion a month ago https://itch.io/t/69422/about-the-mouse

**Comment by nesbox** [comment]
you can define cursor sprite in _config.lua_ (color=0 used as transparency)

![cursor](https://cloud.githubusercontent.com/assets/1101448/25859244/94cf8378-34e6-11e7-808a-bf91797c2b9b.gif)

**Comment by trelemar** [comment]
Perfectly implemented :)

**Comment by nesbox** [comment]
also you can define _mouse cursor sprite_ (foreground sprite) from LUA by calling `poke(0x3FFB,index)`, it'll draw system cursor if _index=0_

```
64K RAM layout
--------------
0000-SCREEN
3FC0-PALETTE
3FF0-PALETTE MAP
3FF8-BORDER COLOR
3FF9-SCREEN OFFSET
3FFB-MOUSE CURSOR SPRITE
3FFC-(reserved for future use)
4000-SPRITES
8000-MAP
FF80-SOUND REGISTERS
FFC8-PERSISTENT MEMORY
```

done in .24
