### ISSUE TITLE
Feature: Custom colors defined in metadata for sprites and palette in sprite editor

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#119]
It is confusing when I define my own palette in metada like a grayscale colors and then I am using system palette when creating a sprites. Setting my own palette as system palette in turn makes UI less readable.
So I think it would be better to use a system palette only for UI and code, and  to use a custom palette (read from metadata) for palette and sprites in the sprite and map editor.

Diferences between: custom palette set as system palette, system palette, system palette with custom palette:
![democolorpallete](https://cloud.githubusercontent.com/assets/17261132/25776528/fe32e468-32c0-11e7-925c-b3ca4854cb37.gif)

**Comment by nesbox** [comment]
Unfortunately it can't be done with current implementation, the problem is that video RAM is the same for editor and game and uses same 16 colors.
Try to use `import/export sprites` with external editor

**Comment by Crutiatix** [comment]
I understand. 👌  I got an alternative idea that could solve problem of ugly colors of UI when using custom system palette. Would by possibe to add to config file a table (like the code table) that defines colors of UI ?

**Comment by nesbox** [comment]
ok, will add a table with colors

**Comment by nesbox** [comment]
added PALMAP variable to the config.lua, use it to remap system UI colors

``` lua
THEME =
{
 PALMAP = "0123456789abcdef",
 ...
}
```
![palmap](https://cloud.githubusercontent.com/assets/1101448/26105492/d44d1e16-3a4a-11e7-9a78-966b7911c307.gif)

done in .25
