### ISSUE TITLE
Feature: Colored output of trace()

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#121]
It would be useful to have option to set color of trace() output to make a different informations more distinguishable in console.

**Comment by nesbox** [comment]
I'll add color parameter `trace(output, color)`

**Comment by nesbox** [comment]
added _color_ parameter `trace text [color=15]`
``` lua
for i=0,15 do trace("hello",i)end
function TIC()end
```
![image](https://cloud.githubusercontent.com/assets/1101448/25850582/8799c6ac-34cb-11e7-861a-61d61b3a77b6.png)

done in .24
