### ISSUE TITLE
Feature: Color picker and other keyboard shortcut in sprite editor.

### ISSUE THREAD

**Issue by harrisyu** [nesbox/tic.computer#124]
Is better to have keyboard shortcut to pick color , also for tools.

**Comment by AlRado** [comment]
You can use click on the mouse wheel to get the color )

**Comment by harrisyu** [comment]
Ok, get it, middle mouse button to pick color works on desktop, but must consider about andriod device.

**Comment by hseiken** [comment]
I'm wondering if there's shortcut keys we don't know about....?

**Comment by nesbox** [comment]
Added _color picker_ tool, also shortcuts:
```
PENCIL       - 1
COLOR PICKER - 2
SELECT       - 3
FILL         - 4
FLIP HORZ    - 5
FLIP VERT    - 6
ROTATE       - 7
ERASE        - 8
```
![image](https://user-images.githubusercontent.com/1101448/26875162-49469734-4b89-11e7-8b55-c702d1608cb1.png)

done in .27
