### ISSUE TITLE
Sprite editor enhancements

### ISSUE THREAD

**Issue by Viza74** [nesbox/tic.computer#128]
A couple of suggestions for the sprite editor:
- Be able to change the size of brush in a couple of steps
- change the color of the brush border, when it’s over a white area, because it is hard to see now
- add shortcut keys for the drawing tools (maybe 1-brush, 2-select, 3-fill, or just the first letters, or maybe the photoshop shortcuts)
- it is hard to see which tool is selected (the icon is just losing it’s one pixel shadow) Consider using something more visible - changing the color, or inverting the selected tool’s icon, etc.
- Still for the previous thought: Maybe even change the cursor for the selected tool

**Comment by trelemar** [comment]
It should probably also be noted that the bucket icon appears to be flood fill, actually acts as color replace.

**Comment by nesbox** [comment]
- added brush size slider
- brush border has two colors black and white
- added shortcuts: 1-brush, 2-select, 3-fill...
- added arrow over selected tool
- fixed flood fill

![image](https://user-images.githubusercontent.com/1101448/26884047-8367a156-4ba7-11e7-9b79-836f610f2701.png)

done in .27
