### ISSUE TITLE
Change screen offset in every scanline

### ISSUE THREAD

**Issue by Viza74** [nesbox/tic.computer#129]
I see that in 0.24 the background color can be changed in the scanline function which is nice (copperbars FTW :) )
It would be nice to be able to also change the screen offset (0x3FF9) in every scanline for some king of glitch effect, or maybe scroll-out-scroll-in screen changes.

**Comment by nesbox** [comment]
``` lua
shake=0
d=4
function TIC()
	if btnp()~=0 then shake=30 end
	if shake>0 then
		poke(0x3FF9+1,math.random(-d,d))
		shake=shake-1		
		if shake==0 then memset(0x3FF9,0,2) end
	end
	cls(12)
	print("PRESS ANY KEY TO GLITCH!",54,64)
end

function scanline(row)
	if shake>0 then
		poke(0x3FF9,math.random(-d,d))		
	end
end
```
![glitch](https://cloud.githubusercontent.com/assets/1101448/26396961/65fab372-407d-11e7-90da-7c9b08ded691.gif)


done in .25
