### ISSUE TITLE
[Web export] Sound lags

### ISSUE THREAD

**Issue by Tinchetsu** [nesbox/tic.computer#13]
When playing a sound, after some time, it starts lag. And every time you keep playing sounds it lags more and more.

How to reproduce:
Any sound will starts to lag. Just open the sfx editor and press a key on the piano. At first there is a small lag. Keep pressing more keys, and the lag time starts to increase with every key pressed.
After some time, it will be a lag like 2 or 3 seconds on each key press.

Tested in Windows 7 with Chrome, Firefox and Opera. All with the same result.

**Comment by nesbox** [comment]
I don't have any lags on my PC.
Could you please try to reproduce it on other systems?
Also pls let me know what do you see here http://webglreport.com/
Thanks.

**Comment by Tinchetsu** [comment]
I tested on mac, also with the same result. Tested with chrome, firefox and opera. So, maybe is not something related to systems? Maybe its due to my location? I'm from Buenos Aires, Argentina. (but I'm just making guesses, not sure how this works :) )

I uploaded 2 videos showing the problem (sorry for the bad quality of my phone).
https://www.youtube.com/watch?v=YhKWBn8gyfI
https://www.youtube.com/watch?v=yL5uuOwO4_o

Attached two screenshots with webgl reports, one with chrome and the other with firefox, on Win7

![win7-firefox](https://cloud.githubusercontent.com/assets/10901731/22246856/a448a948-e215-11e6-8e59-ffa00985a8f7.png)
![win7-chrome](https://cloud.githubusercontent.com/assets/10901731/22246855/a4489656-e215-11e6-9da8-815cf5218bb9.png)

**Comment by nesbox** [comment]
Hmm, seems the problem is in refresh rate frequency
could you please run test here http://codepen.io/GabbeV/pen/CsoGt

**Comment by Tinchetsu** [comment]
I'm getting a constant 60
https://www.youtube.com/watch?v=WM3q2Zt0PlY

**Comment by nesbox** [comment]
ok, it's not a frequency
please unpack, run .html file in your browser and send me screenshot
[html.zip](https://github.com/nesbox/tic.computer/files/726738/html.zip)

Thanks for your patience :)

**Comment by Tinchetsu** [comment]
Here is the screen.
And no problem! I'm glad to help in this cool project! :)

![screen](https://cloud.githubusercontent.com/assets/10901731/22248451/68ae9b7e-e21d-11e6-9d25-c266ed825a80.png)

**Comment by nesbox** [comment]
yes, I caught the bug :)
so, the problem is in TIC sound initialization module, will fix it in 0.16.0

Thank you very much :)

**Comment by nesbox** [comment]
I made a hotfix to test sound on your side.
Please [html.zip](https://github.com/nesbox/tic.computer/files/726769/html.zip)

**Comment by Tinchetsu** [comment]
Nice! With that last html, it works perfectly. Just like the .exe version!

**Comment by nesbox** [comment]
Great, thanks :)

**Comment by nesbox** [comment]
fixed
