### ISSUE TITLE
Change the startup sound

### ISSUE THREAD

**Issue by Viza74** [nesbox/tic.computer#130]
Right now the startup beeps sounds like an error beep (to me at least - I always wincing and look for an error dialog when I hear it :) )
Could it be changed to something... hmm... friendlier? Uplifting?  Motivational? :)

Maybe we could ask Tromino, the master of TIC-80 music :) to create a nice TIC-80 jingle.

**Comment by Crutiatix** [comment]
The startup sound is customisable in config file, in THEME.START.

**Comment by Viza74** [comment]
Hmm I did not realized that i can change that there, thanks for the tip.
I still think the default one should be something less error-sound-y :) so I leave this issue/suggestion open, but this not something important, so just close it if you want.

**Comment by darkhog** [comment]
I dunno. I kinda like the sound. It's sounds like TIC-80 is happy to see me again.

Be glad it doesn't play For Elise on startup (google pc plays for elise if you don't know why you should be glad it doesn't do that).

**Comment by Viza74** [comment]
I didn't mean to use minutes of awful music :)
In the "old times" on the pc (not really, even in todays computers)  more than one beep meant error (I just looked up: three short beeps means "Base 64k ram failure" on AMI bios and "Motherboard failure" on Dell...) 
So maybe it is just the old habits in me, that generates negative associations. :)

**Comment by nesbox** [comment]
added new startup beep made by RushJet1
``` lua
	START =
	{
		SFX="030003000304030403070307030c030c090009000900090009000900090009000c000c000c000c000c000c000c000c000f000f000f000f000f000f00030200008000",
		NOTE="C#4",
		VOLUME=15,
	},
```

done in .29
