### ISSUE TITLE
Using rotated and flipped tiles in the map editor

### ISSUE THREAD

**Issue by Viza74** [nesbox/tic.computer#131]
I guess this is a no-go (because of the need of changing the map data structure/drawing/etc), but I just put it out here.
Could we use rotated and flipped tiles in the map editor?
Could save on the number of needed tiles in a lot of games.

**Comment by Effer** [comment]
I thought the same time ago, but as you said it will broke the map structure. We discussed about sacrifice some of the map room, but it'll also brake the perfect fitting of the memory. 
Not an easy choice.

**Comment by Viza74** [comment]
Thought a bit more about it, and arrived at the conclusion that it is not really worth to do it.
Screws the layout of the map memory, and (depending on the implementation, but most likely) even wastes memory not saving. And besides, not even "retro" :)

**Comment by trelemar** [comment]
According to the map wiki page it is possible to do flip and rotated sprites with the remap call back function. I'd love to see a simple demo for how to do that though.

**Comment by nesbox** [comment]
simple demo _How to rotate sprites on map rendering_
``` lua
local t=0
function TIC()
 cls(12)	
 map(0,0,30,17,0,0,0,2,function(id) return id,0,(t%60)//15 end)	
 t=t+1
end
```
callback format is `remap ( [tile] [x] [y] ) -> tile [flip=0] [rotate=0] `

![remap](https://cloud.githubusercontent.com/assets/1101448/26165626/50f234f8-3b39-11e7-9358-ac0d08b06f4d.gif)

**Comment by trelemar** [comment]
Oh you just return multipule values! I was over thinking it. Thanks!

**Comment by Viza74** [comment]
I understand how the reamp function works (I think), but don't understand in what situations could it be useful? Could somebody give some examples for me?
All I can come up is related to changing tiles (open/closed doors, or damaging environment), not nothing for the rotation and flip. (and changing tiles sounds easier just modifying the map)

Using it for ratations/flip sounds... tedious. 
Lets assume I want to create a top-down room, but (to save tiles) only using a horizontal wall and a single corner tile. So to draw the room I need to rotate the wall tile 90 for the left wall, 180 for the bottom wall, 270 for the right wall, and the same for the corner tile.

I can't really see how the room will look ingame in the map editor, since it will be drawn with all tiles in it's original rotation.
I need a way to keep the list of tiles in the code (by manually noting the coordinates) so the remap function can identify the tiles to be rotated, since there is no way to assign metadata to the tiles AFAIK.

Or am I missing something?

**Comment by trelemar** [comment]
@Viza74 You would need to check the tile's neighboring tiles. No need to list the positions of each tile and rotate from there.

For example, if your tiles east neighbor is a floor, it's north is a wall, it's south is a wall, then you know it is a left wall. If your tile's east and west neighbor is a wall, and it's south is a floor, it's a top wall. Ect.. Once you figure out it's neighboring tiles, rotate from there. My game Amrogue does something similar before the rotation remap was implemented where it applies rotation with msets. The function is called pretty_map() in Amrogue if you'd like to check it out and build from there.

**Comment by Viza74** [comment]
Ohh, yeah, thats a good idea.
Your suggestion is more from a design-design direction ("these will be walls, and here the player can walk"), and I originally approached the problem from a visual direction ("this is how I want my level look"), which is probably why I didn't see that solution.

But yeah, that's a perfectly valid use case for remap, thank you!
