### ISSUE TITLE
HOTFIX REQUEST. Remap is broken.

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#134]
The remap function is broken in v0.24.0. You can try it with the demo or watch my video before i realized what was going on.
http://tic.computer/play?cart=9

https://youtu.be/U4hYQBSyaTE

**Comment by nesbox** [comment]
_scale_ param was added in .24
`map [x=0 y=0] [w=30 h=17] [sx=0 sy=0] [colorkey=-1] [scale=1] [remap=nil]`
fixed on the website
thanks

**Comment by trelemar** [comment]
Wow. I missed that one.
