### ISSUE TITLE
0.24 crash with moonscript error

### ISSUE THREAD

**Issue by harrisyu** [nesbox/tic.computer#135]
here is the code that have error:
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: moon
-- input:  gamepad

ani={}
with ani
 wheel={50,{488,489,490}}
trace ani.wheel[1]
  
export TIC=->
 cls 11

in 0.23 it show every time when run that "attempt to index nil value", it's ok.
in 0.24 it has no feedback on console, sometimes show same error message, but will crash tic-80 when you execute the same code within 10 times.
I using windows 10.

**Comment by nesbox** [comment]
made a hotfix, thanks
[tic_0.24.0_hotfix.zip](https://github.com/nesbox/tic.computer/files/998798/tic_0.24.0_hotfix.zip)

**Comment by harrisyu** [comment]
Thanks for the quick hotfix, but now all trace out put is "trace out".

**Comment by nesbox** [comment]
Oops, another one fix :)
[tic_trace_fix.zip](https://github.com/nesbox/tic.computer/files/999641/tic_trace_fix.zip)

**Comment by nesbox** [comment]
done in .25
