### ISSUE TITLE
0.24 Rendering maps on linux x64 

### ISSUE THREAD

**Issue by nihirash** [nesbox/tic.computer#136]
Using fedora 25 with gnome on wayland.

![screenshot](https://cloud.githubusercontent.com/assets/5459892/26036650/fc9fc088-38e9-11e7-95ee-a31ab541bd27.png)

As seen - rendering maps via map function broken(0.23 version works propelly).

**Comment by trelemar** [comment]
scale was added to the map function before the remap parameter, if your using remap it won't work.

**Comment by trelemar** [comment]
https://github.com/nesbox/tic.computer/issues/134

**Comment by nihirash** [comment]
All fine! thanks!
