### ISSUE TITLE
[REQUEST] Fill a portion of the map with a specific tile

### ISSUE THREAD

**Issue by fmaida** [nesbox/tic.computer#138]
Hello. TIC-80 is great, but I'd like to ask you a question.
Inside the map editor I'd like to fill a portion of the map with a specific tile.

For example, starting from this map:

![tic-80_tiny_computer_0_24_0_dev__example_tic_](https://cloud.githubusercontent.com/assets/605017/26106593/a39b3a2c-3a46-11e7-9c62-707a469875db.png)

I'd like to fill the area inside the container like this:

![tic-80_tiny_computer_0_24_0_dev__example_tic_ 2](https://cloud.githubusercontent.com/assets/605017/26106611/b2b63110-3a46-11e7-80f1-0bf351b722a8.png)

without having to manually put each tile.
Is it actually possible?

Thank you and best regards

**Comment by nesbox** [comment]
It's not possible yet, I'll try to add something. Thanks.

**Comment by trelemar** [comment]
Back when I was working on a pixel art editor I found this recursive flood fill function http://lodev.org/cgtutor/floodfill.html#4-Way_Recursive_Method_floodFill4 if it's useful for @nesbox

**Comment by nesbox** [comment]
done with #178 
closing
