### ISSUE TITLE
Bugs in the windows store version 0.15.0

### ISSUE THREAD

**Issue by harraps** [nesbox/tic.computer#14]
It seems that the windows store version is quite bugged.
for example:

- the key 'O' open the search function in the text editor.
- whatever we run in the terminal, it will interpret it as 'run'

There might other bugs, but I cannot look further.

**Comment by nesbox** [comment]
Seems to your CTRL buttons is always in pressed state :)
Do you reproduce the bug every time you run TIC?

**Comment by harraps** [comment]
that was the issue. But it's weird that It considered my CTRL as pressed, when actually it wasn't.
