### ISSUE TITLE
Sfx editor improvements

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#140]
It's just my opinion but there are a couple of thing in the Gui that I found counter intuitive:
 - Envelopes tab: The white buttons preview shouldn't flat the wave form selector when left clicked. Maybe "right click"? Another button? Left click should only switch to waveform editor?
- Even, is not so intuitive the function of envelopes grid. Maybe align the preview icons with the relative rows in the grid?
- Waveforms tab: Here click on the white buttons preview, change the wave form in the editor but doesn't  allow to play just this waveform to listen at the modified sound.

Just a couple of thought from an user without experience in tracker.

**Comment by nesbox** [comment]
yes, I have to admit it's not convenient, needs to be redesigned...

**Comment by nesbox** [comment]
redesigning WAVE tab in SFX Editor

![image](https://cloud.githubusercontent.com/assets/1101448/26461513/0224191a-4186-11e7-9b21-556e2448f678.png)

**Comment by Effer** [comment]
Well done! It seems more clear to me.

**Comment by nesbox** [comment]
done in .25
