### ISSUE TITLE
TIC doesn't load demo carts on win7

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#142]
also opens _My Documents_ folder on `folder` command

**Comment by AlRado** [comment]
I had this problem on one of the computers with Win 7, but the system was old and worked poorly, I reinstalled it and problem was resolved )

**Comment by nesbox** [comment]
made a fix
[tic.zip](https://github.com/nesbox/tic.computer/files/1035386/tic.zip)

**Comment by nesbox** [comment]
made a fix
and build for test - [tic.zip](https://github.com/nesbox/tic.computer/files/1035410/tic.zip)

**Comment by AlRado** [comment]
Now I have no errors with the palette.
