### ISSUE TITLE
Screenshots with Hotkey

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#144]
Taking true 240*136 screenshots isn't possible currently. The current process for me is to set the cover image, export then scale the image in a external image editor. But what if I'd like to take a screenshot of the code, sprite ect... editor? Maybe you could even have a "screenshot scale" option in config that will automatically scale the image saved. GIF recording would be amazing as well.

**Comment by Effer** [comment]
I vote for this, with Gif recording.

**Comment by nesbox** [comment]
You can take 240x136 screenshot by pressing **F8**
also you can change the scale in _config.lua_
``` lua
...
SCREENSHOT_SCALE = 1
```
it won't work with scanline effects
also I'll open GIF recording in a separate issue

done in .26
