### ISSUE TITLE
Bug: TIC is decreasing volume of all sounds in system windows (10)

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#145]
I noticed this bug earlier, but didn't pay more attention to it. 
TIC (native windows or browser HTML5 version too) **decreases volume of all sounds in system roughly to half** except to a volume of TIC self. However settings of volume in system sound mixer are unchanged.
Everyting is alright directly after closing TIC.

**Comment by jackwilsdon** [comment]
Try changing "When Windows detects communications activity" to "Do nothing" under the Windows sound settings.

**Comment by Crutiatix** [comment]
Closing this issue. This problem is behavior of the browser google chrome, not of TIC.
