### ISSUE TITLE
Linux version stores data separately per version

### ISSUE THREAD

**Issue by snail-prime** [nesbox/tic.computer#147]
![image](https://cloud.githubusercontent.com/assets/12587624/26476782/039c7c66-418f-11e7-8eb4-a9a809d35703.png)
Using the Linux version (installed through itch, if that matters), there is a separate folder for each version's save data. I either have to copy the files manually or redo all of my config on every update.

**Comment by nesbox** [comment]
TIC is unstable and I do it especially to save user files, going to remove the separate folders with a stable release.

**Comment by snail-prime** [comment]
Makes sense, thanks.

**Comment by nesbox** [comment]
so, closing then
