### ISSUE TITLE
Error message when run out of code space

### ISSUE THREAD

**Issue by Viza74** [nesbox/tic.computer#149]
I use an external code editor, and just spent a couple of minutes trying to decipher cryptic error messages about missing "end"'s till I finally realized that the actual problem is that I run out of code space, and my code got truncated on load.
I guess that's not a problem using the built in code editor, since it is just stops accepting new letters, but maybe an a descriptive error message on load could help the ones using external editors to avoid some frustration when bumping in the limit.

(Also: the internal editor is quite slow when trying to edit 65k code... I takes about 3 seconds to change a single character. Since I can't imagine anybody using the internal editor to write that much code, I guess that not necessary an issue, so I just mention here.)

**Comment by nesbox** [comment]
added error message when run out of code space

![image](https://user-images.githubusercontent.com/1101448/27886330-4355ad30-61e4-11e7-9d80-9fc0dcf4ca4d.png)

done in .29
