### ISSUE TITLE
pagination for dir command

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#150]
If you have more carts that screen have lines, they'll just roll over the screen. Perhaps pagination would help. I'm thinking about dos-like /p switch for the dir command. Other function that would benefit from such is help, because it's at the verge of overflowing as well.

**Comment by trelemar** [comment]
You can now scroll within the terminal with the mouse wheel or with 2 fingers on Android. That should solve the problem and should be safe to close this issue now.
