### ISSUE TITLE
Android: Tracker (Music Editor) doesn't work properly on android. 

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#152]
Even if you have keyboard opened, it'll only enter sharp notes from number keys. When pressing z,x,c and so on, nothing happens. Possible solution would be a "piano" on the bottom half of the tracker (at the cost of pattern space, which would then need to be scrollable), similar to the one in the sound editor.

**Comment by trelemar** [comment]
Already have an issue for this. Closing to avoid duplicate.

https://github.com/nesbox/tic.computer/issues/106

**Comment by nesbox** [comment]
And there will be a separate _Piano Mode_ optimized for touch input
