### ISSUE TITLE
Update check or autoupdater

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#153]
I'd like if TIC-80 was checking for updates and either autodownload them and install or simply inform user of the new update, so e.g. when outdated version is updated, upon loading it, it'll show something like

    type help for help.
    A new version is available to download. Your version $(InstalledVersion), newest version $(NewestVersion)

**Comment by hseiken** [comment]
I'd like for exactly 0% of this to be implemented.  

Reasons:
Autoupdates break some people's systems without their say, introduce new bugs, destroy their work in progress through force of change, etc.

Autoupdates = very no for me.

**Comment by trelemar** [comment]
This was also discussed awhile back here:

https://github.com/nesbox/tic.computer/issues/46

**Comment by darkhog** [comment]
Oh so you don't even want the software to inform you that the new version is available? Because if either of those is implemented it's fine by me. After all, this issue is called update check OR autoupdater. So if it just informs you about new version and it's up to you to dl it, it's fine by me.

**Comment by nesbox** [comment]
`check_new_ver` flag will be added to the _config_

**Comment by nesbox** [comment]
added **CHECK_NEW_VERSION** to the _config_
``` lua
...
CHECK_NEW_VERSION = true
```
and you'll see the following message if a new version is available
![image](https://cloud.githubusercontent.com/assets/1101448/26604685/d5a1c0f6-4593-11e7-808f-2e2d9f07b80f.png)

done in .26
