### ISSUE TITLE
If custom cursor is defined in  config.lua, it still doesn't allign with the resolution

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#155]
Originally I was about to do an issue about having to use system cursor, but then I've found this and set it myself: https://github.com/nesbox/tic.computer/issues/116

Problem is that when custom cursor is set, it doesn't align to screen pixels: http://i.imgur.com/TNemrmr.png - see, the custom cursor is between two pixels (a thing physically impossible in a real machine. What I'd like to see is cursor aligning perfectly to screen grid, just like one in Pico-8, if a custom one is defined. I prefer custom cursor as it increases immersion, but things like it not being aligned to screen breaks it again.

**Comment by nesbox** [comment]
ok, will add `pixel-perfect` flag to the _config_

**Comment by Effer** [comment]
Not strictly related, but what about adding a way to move the mouse cursor also? something like **mouse(x,y,?p)**

**Comment by nesbox** [comment]
@Effer I can, SDL has [SDL_WarpMouseInWindow](https://wiki.libsdl.org/SDL_WarpMouseInWindow) function, but why do you need it? provide example pls :)

**Comment by Effer** [comment]
@nesbox 
- Snapping to GUI element 
- Move cursor to OK Button in Dialog (some old software do that (DOS era))
- In game tutorial

I believe everything could also be done by hiding cursor and moving a sprite. It just come in my mind reading the topic, so I trow it here to hear some opinion.

**Comment by nesbox** [comment]
added **PIXEL_PERFECT** field to the _config_
``` lua
THEME =
{
...
	CURSOR = 
	{
		SPRITE = "0000000000000000000000000000000000000000000000000000000000000000",
		PIXEL_PERFECT = true,
	},
...
```

done in .26

PS. let's discuss do we really need to move mouse cursor from api?

**Comment by Effer** [comment]
Probably not.  I can see only very few real cases.

**Comment by darkhog** [comment]
It may be useful if someone decides to make 3D game in TIC (they did these for Pico which has far less power) for centering cursor. That might need mixed input though (either kb+mouse or gamepad+mouse).
