### ISSUE TITLE
Restore sprites and map data on every game start

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#159]
also, add API method to save modified in runtime sprites/map data

**Comment by nesbox** [comment]
sprites/map data restores on every startup
added `sync()` api to save modified in runtime sprites/map data
done in .26

**Comment by Effer** [comment]
@nesbox this is the fastest new feature/issue implementation I've ever saw :)

**Comment by nesbox** [comment]
yes, I implemented it before the issue was created :)
