### ISSUE TITLE
Ненулевое начальное смещение в редакторе карт

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#16]
Приветствую! При загрузке картриджа и последующем переходе в редактор карт, текущая карта отображается не со смещением 0,0 и не последняя редактируемая, а по середине и со сдвигом. В равом нижнем углу окна выбора карты возникает небольшой прямоугольный артефакт.

**Comment by nesbox** [comment]
Привет.
На самом деле карта специально отображается со смещением чтобы показать что она зациклена, т.е. координата 0:0 граничит с 239:135 и карта бесконечно прокручивается если использовать правую кнопку мыши для перетаскивания. В режиме глобального просмотра карты в красном прямоугольнике отображается текущее положение экрана, т.е. "небольшой прямоугольный артефакт" в правом нижнем углу это и есть текущее положение экрана, просто он вылез за пределы глобальной карты.
В общем, это не баг, все так и задумано.
Возможно стоит устанавливать начальный экран в положение 0:0 на старте, чтобы не вводить в заблуждение?

PS
основная аудитория проекта англоязычная, так что предлагаю создавать баги и общаться на английском.

Спасибо.

**Comment by KochkinBochkin** [comment]
>Возможно, стоит устанавливать начальный экран в положение 0:0 на старте, чтобы не вводить в заблуждение?
Думаю, стоит. Вчера 3 часа рисовал карту, выбрав перед этим смещение 0,0. Сохранил, потом открыл через некот. время - карты нет! Потом разобрался, конечно, но шок был))
Насчет языка багрепортов я понял, следующие будут на ломаном английском)

**Comment by nesbox** [comment]
ок, так и сделаем

**Comment by nesbox** [comment]
fixed in 0.17.0
