### ISSUE TITLE
You shouldn't have to move carts manually after an update

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#160]
Imagine my surprise when I've found out that after downloading 0.26 and running it I've found my carts simply gone. Well, they weren't actually gone, but in different folder which as I've found out was version-dependent (%appdata%\TIC-80\<version number> in case of windows).

I think it would be better if the program would store carts in a directory independent of TIC-80 version number (I propose either %appdata%\TIC-80, Documents\TIC-80 or the directory you've unzipped TIC-80 to) and if this gets implemented, move the carts automatically from previous directory so no manual move would be necessary on new version.

**Comment by Effer** [comment]
@nesbox use this way to store carts as precaution during the Beta phase.  It's not the first time this issue is raised, probably is still not the time.

**Comment by trelemar** [comment]
https://github.com/nesbox/tic.computer/issues/147
