### ISSUE TITLE
trace() is useless for truth/false values

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#163]
Try the following code:

    trace(2+2==4)

It will return always nil instead of true/false which makes trace() useless for debugging conditions. It will return nil in the case that conditional would result in false as well such as this: `trace(3-3==math.sqrt(math.pi))`

**Comment by Crutiatix** [comment]
Use function tostring:
```lua
trace(tostring(2+2==4))
```
But yes, it could be regular behavior of trace function.

**Comment by trelemar** [comment]
```trace(tostring(2+2==4))```

**Comment by chestfest** [comment]
^

**Comment by nesbox** [comment]
added `tostring` behavior
done in .27
