### ISSUE TITLE
loadmusic/loadsfx/loadsprites/loadmap/loadcode commands

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#164]
They'd work like ordinary load command, but would only load appropriate section so e.g.

loadmusic (cart name) would load only music data from a cart and replace currently loaded music, loadsprites would do same for sprites and so on.

This would make possible to create "library carts" that contain music/sounds/graphics you often use in games you make but usually don't need until long into development cycle when replacing just one thing via copy-pasting would take too much time.

Mostly quality of life stuff but I think this would be useful.

**Comment by nesbox** [comment]
I'll add the third parameter to `load` command
`load cart.tic [ music | sfx | sprites | map | code ]`
Great idea, thanks 👍

**Comment by darkhog** [comment]
Sounds good. Probably adding parameters is better for cleanliness of the command interpreter code.

**Comment by nesbox** [comment]
so, you can load _sections_ from other carts, even from the website
`load cart.tic [tiles | sprites | map | cover | code | sfx | waves | music | palette]`
done in .27
