### ISSUE TITLE
[0.26.0 dev Windows 10 exe] font function crashes program when given nil value

### ISSUE THREAD

**Issue by Terumoc** [nesbox/tic.computer#165]
Hello! On the standalone Windows version of TIC-80, when you call font() with a value that is nil it crashes the program. 

This happens whether it is directly -- `font(nil)` -- or with a variable that has not been defined such as `font(foo)` right at the beginning of the script.

The HTML5 version seems to ignore it completely.

**Comment by nesbox** [comment]
fixed here #163
