### ISSUE TITLE
Palette editor

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#166]
ability to edit cartridge palette directly from the Sprite Editor

**Comment by nesbox** [comment]
added Palette Editor with RGB sliders and copy/paste buttons
![image](https://cloud.githubusercontent.com/assets/1101448/26826864/4a5dbc7c-4ac3-11e7-889f-7783862ce582.png)

also, removed `-- pal:` metadata definition because all the palette data saves to the cartridge now

done in .27

**Comment by nesbox** [comment]
one more thing, RGB values are in normal order in VRAM now, were BGR

**Comment by trelemar** [comment]
Ahh. I was going to ask about how that worked with the palette metadata. Is there a way to set a pre-defined palette now without setting each color in the editor?
