### ISSUE TITLE
Serious "loss of data" issue with new command

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#168]
If you do the following:

1. Load any cart
2. Issue new command to create a new cart
3. Press Ctrl+S to try and save it

...it'll overwrite previously loaded cart! I've almost lost my Heavy Duty Sprinkler port due to this. Good thing I had a backup!

**Comment by trelemar** [comment]
Possible solution from another open issue:

https://github.com/nesbox/tic.computer/issues/59

**Comment by nesbox** [comment]
fixed in .27
