### ISSUE TITLE
Make config.lua editable from TIC

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#17]
The new config.lua file is visible with the dir command but is not editable from TIC.

![image](https://cloud.githubusercontent.com/assets/1007007/22396796/c69b8380-e562-11e6-86f0-0e6ea705fc51.png)

It would be nice to allow edit it. It doesn't look so bad in the editor:
![image](https://cloud.githubusercontent.com/assets/1007007/22396813/41cb2a38-e563-11e6-95b8-17b99b0e2c2b.png)

**Comment by nesbox** [comment]
Yes, thought about it.
Maybe I will add CONFIG command to edit the config.lua file in only code editor.

**Comment by nesbox** [comment]
done in 0.17.0
added console command: config [save] and CTRL+S hotkey

![config](https://cloud.githubusercontent.com/assets/1101448/22511769/c0f4b9ae-e8a7-11e6-97b8-acbc647ae152.gif)
