### ISSUE TITLE
wrong pallete when import sprites from gif.

### ISSUE THREAD

**Issue by harrisyu** [nesbox/tic.computer#171]
0.27 dev 
Wrong pallete when import sprites from gif.
Same problem when using "-sprites" in command line.
![qq 20170608225259](https://user-images.githubusercontent.com/4844464/26934924-36a6d264-4c9d-11e7-9ffe-33681b830dfa.png)

**Comment by nesbox** [comment]
made a hotfix, in .28 all will be ok
[tic_0.27.1_hotfix.zip](https://github.com/nesbox/tic.computer/files/1061406/tic_0.27.1_hotfix.zip)

thanks

**Comment by harrisyu** [comment]
It's ok now, thank you.

**Comment by nesbox** [comment]
closing on 0.27.1
