### ISSUE TITLE
Can't load code with -code argument on 0.27.0

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#172]
Using latest I got a black screen. It doesn't crash simply it stay there. Win 10

`tic.exe -code test.lua`

**Comment by nesbox** [comment]
made a hotfix
[tic_0.27.1_hotfix_for_172.zip](https://github.com/nesbox/tic.computer/files/1062522/tic_0.27.1_hotfix_for_172.zip)

Thanks

**Comment by fmaida** [comment]
I have the same problem on my Mac under Visual Studio Code

**Comment by nesbox** [comment]
@fmaida I released 0.27.1 hotfix
closing
