### ISSUE TITLE
realtime trace() output to console

### ISSUE THREAD

**Issue by to90zeroblue** [nesbox/tic.computer#173]
trace() only displays after the program is finished running. It would be really useful to get trace() to output in real time to the terminal, like windows powershell or another terminal emulator.

**Comment by darkhog** [comment]
Going to +1 this, however you can pipe trace output to file by running tic.exe > log.txt (or tic >log.txt in unix systems such as mac or linux). Dunno if it outputs in realtime, but if it does all you'd need to do is an editor or file viewer capable of detecting changes to the specified text file and auto reloading it.

Obviously this is just a workaround with no guarantee of working, but still, doesn't hurt to try.

**Comment by trelemar** [comment]
https://github.com/nesbox/tic.computer/issues/188

Same issue here correct?

**Comment by nesbox** [comment]
yes, #188 is the same

**Comment by nesbox** [comment]
realtime trace works on Linux/MacOSX, if I run TIC from Sublime editor it also shows output in realtime

![trace](https://user-images.githubusercontent.com/1101448/30482627-89b14e80-9a2c-11e7-9279-42717fb1d91d.gif)

so, I think it's Windows specific
