### ISSUE TITLE
Editor should have a separate palette.

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#179]
Because with shared palette deal, this is what happens: http://i.imgur.com/ixGEgrK.png

Not too terrible to look at, but I imagine some people working with pretty crazy palettes which would incur usability damage on the editor (such as a palette that has similar colors for background and foreground items).

**Comment by Jummit** [comment]
Oh yeah, that would be very cool. Maybe in a config file like the key textures.

**Comment by trelemar** [comment]
There is the palette map in config that allows rearranging the color order for the editors.

**Comment by Jummit** [comment]
how is it called?

**Comment by trelemar** [comment]
It's defined in config line 184.

**Comment by Jummit** [comment]
and how can i change it? it is 0123456789abcdef,  but i have no clue what that means

**Comment by trelemar** [comment]
That's the default color arrangement. Letters a-f represent colors 10-15.

**Comment by Jummit** [comment]
so what does the numbers do?

**Comment by trelemar** [comment]
You change the order of them to the color map you want. fedcba987654321 would reverse the palette for example.

**Comment by Jummit** [comment]
And is there a table which color does what in the editor? For example color one does text, and so on?

**Comment by darkhog** [comment]
Yes, but rearranging palette mapping in config doesn't solve the issue - it may for one game, but once you start developing another one with a different palette, colors will clash again.

**Comment by trelemar** [comment]
I can't see this happening, TIC's display has a 16 color limit, and only through scanline effects can you achieve more than 16 on the screen. I recommend using the palmap in config the make the editors usable with your custom color palette.

**Comment by darkhog** [comment]
TIC-80 "display" doesn't exist. Editors are drawn using SDL calls, not as a TIC Lua code.

Also I set the palmap for my game and then what? I'll have to set it again for every game I make? Or for that matter, for any game/demo I'll look at? Because I'm not going to stick to one palette only, like I had to with Pico.
