### ISSUE TITLE
Hotkey for sprite shift.

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#18]
It is necessary hotkeys to cyclic image shift  in the sprite edit window.

**Comment by nesbox** [comment]
Try to use SELECT tool and use arrows to move selection.

**Comment by KochkinBochkin** [comment]
It is not work, unfortunately.

**Comment by nesbox** [comment]
Try to make selection less than canvas rectangle and try to move, maybe problem is here

**Comment by KochkinBochkin** [comment]
Yes! Problem is here! Thank you! Fix, please, in next releases)

**Comment by nesbox** [comment]
Thought a lot how to get it work on another way and didn't find a solution.
So I decided to create a demo to show how to shift sprites with selection and arrows keys.

![select](https://cloud.githubusercontent.com/assets/1101448/22565793/88a8e1c6-e99a-11e6-90f8-e3438bb00a76.gif)

Maybe it helps you.

**Comment by KochkinBochkin** [comment]
Ok! Thank You for a demo, Vadim!

**Comment by nesbox** [comment]
close then
