### ISSUE TITLE
I need a sleep function

### ISSUE THREAD

**Issue by Jummit** [nesbox/tic.computer#182]
I dont know how others handle this, but it would be realy nice to have a function that waits, without stopping the music. If there is a way around this, please tell me.

**Comment by nesbox** [comment]
was discussed
https://github.com/nesbox/tic.computer/issues/77

**Comment by darkhog** [comment]
Way around? Sure.

``` lua
waittimer=0
function TIC()
  if waittimer>0 then
    waittimer=waittimer-1
  else
    --normal code there. Set waittimer to any value bigger than 0 to wait that many frames
  end
end
```

**Comment by AlRado** [comment]
```lua
waittimer=5000 --> time in milliseconds
function TIC()
if (time()>=waittimer) then
--normal code there.
end
end
```
I think this option is better, it should work correctly even if the device will work slowly

**Comment by hseiken** [comment]
Is this a request for device sleeping/wakeup routines?

**Comment by darkhog** [comment]
Nope. It's more of some sleep/delay function that wouldn't hang the device, similar to disabling interrupt for a while and reenabling it afterwards.

**Comment by nesbox** [comment]
there won't be a sleep function, pls use a boolean flag
closing
