### ISSUE TITLE
Touch X and Y buttons aren't displayed on mobile (Android) in 0.28.0

### ISSUE THREAD

**Issue by Bentic** [nesbox/tic.computer#186]
The new X and Y buttons in 0.28.0 aren't displayed in touch controls on mobile (Android).

Steps to reproduce:
- launch app
- run new project

Note: when touching where X is supposed to be, it triggers.
But not Y, see issue https://github.com/nesbox/tic.computer/issues/185

**Comment by nesbox** [comment]
fixed in 0.28.1
