### ISSUE TITLE
Add a start frame and end frame to music()

### ISSUE THREAD

**Issue by Bentic** [nesbox/tic.computer#187]
Suggestion to add the possibility to specify a start frame and an end frame when playing a track with music()

Example: music [track=-1] [loop=true] [frame_start=-1] [frame_end=15]
Or music [track=-1] [frame_start=-1] [loop=true] [frame_end=15] if you don't want to change the current order, but since it was just implemented in 0.28.0, I would assume not many people have already started using those parameters.

That way we could play from one frame until the end of the track by omitting the last parameter, or play only one frame by using music(0,true/false,5,5) for instance.

Bonus points if loop==false and frame_start>frame_end, loop once to play the frames in order from frame_start to 15 then from 0 to frame_end and stop playing.
Not sure if it would be useful, but some advanced tracker users might use it someday!

**Comment by darkhog** [comment]
I think this could be achieved with jump to frame/jump to row effect.

**Comment by nesbox** [comment]
partly done in #238 
now _music_ api is
`music [track=-1] [frame=-1] [row=-1] [loop=true]`
you could peek MUSIC POS value by 0x13FFC to detect when frame to stop

closing on .30
