### ISSUE TITLE
bug/feature? add trace() output to console

### ISSUE THREAD

**Issue by to90zeroblue** [nesbox/tic.computer#188]
When running TIC80 through command line, I would like to have outputs from trace() in the terminal window. Maybe a command line argument -t ?

**Comment by nesbox** [comment]
info for me
https://stackoverflow.com/questions/3009042/how-to-view-printf-output-in-a-win32-application-on-visual-studio-2010

**Comment by nesbox** [comment]
close duplicate of #173
