### ISSUE TITLE
Gridlines not visible in the map editor when the background sprite isn't black

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#190]
Maybe you should make the gridlines shift color or use some kind of blend mode.

**Comment by darkhog** [comment]
Agreed. I think grid lines should be drawn always on top with color of each grid pixel being calculated using formula `default grid color XOR color of pixel under`.

**Comment by nesbox** [comment]
not sure about XOR method
![image](https://user-images.githubusercontent.com/1101448/27843704-69c82468-611f-11e7-900c-a53916e2f590.png)

**Comment by nesbox** [comment]
ok, I just draw the grid on top
![image](https://user-images.githubusercontent.com/1101448/27863184-9ab049bc-6191-11e7-9bb2-1827d46e35ca.png)
done in .29

**Comment by AnastasiaDunbar** [comment]
@nesbox But what if you're using a purple background?

**Comment by AnastasiaDunbar** [comment]
Isn't this better?
![image](https://user-images.githubusercontent.com/11806048/27906015-6a48a79a-6274-11e7-80ab-36e2b92fb2e5.png)

**Comment by nesbox** [comment]
controversially, as for me

**Comment by nesbox** [comment]
there another problem, what if a user uses a custom palette (not DB16), how we can calc color for the grid in this case?
