### ISSUE TITLE
Indenting multiple lines at once

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#191]
It would work like this:
1. Select block of multiple lines
2. Press Ctrl+Tab
This will be useful when you want to intend multiple lines to increase readability of your code (e.g. if you were concerned with character limit and as such you've avoided unnecessary white space, but at the end you had plenty of characters left so you've decided to format your code properly)

**Comment by kool601** [comment]
Nice idea, but your spelling of 'indent' is bothering me. No offense, I just have OCD. But yes, this would be a great feature.

**Comment by nesbox** [comment]
it works, but with TAB/Shift+TAB
![tab](https://user-images.githubusercontent.com/1101448/30481697-b678da40-9a28-11e7-965e-4f2f6e188ecc.gif)
