### ISSUE TITLE
Function spr parameters value switched

### ISSUE THREAD

**Issue by eliacoan** [nesbox/tic.computer#195]
When calling spr function specifing the flip parameter specified as stated in wiki
```
0 = No Flip
1 = Flip vertically
2 = Flip horizontally
3 = Flip both vertically and horizontally
```
1 does flip horizontally and 2 does flip vertically: they are switched.
Both 0 and 3 has no problems at all.

**Comment by trelemar** [comment]
Is this a wiki issue or an API issue?

**Comment by eliacoan** [comment]
see this tweet and related thread to answer your question
https://twitter.com/EliaCoan/status/876045905216098312

**Comment by darkhog** [comment]
While it may be a bug in TIC, I've seen carts using flipping so instead the wiki should be updated to not break these carts.

**Comment by eliacoan** [comment]
I really don't know, @nesbox told me to open an issue here ;)

**Comment by Effer** [comment]
I've always thought horizontal flip mean, the result image if a mirror is laid horizontally. I was wrong, it seems all software use it to flip the image moving horizontally from left to right.
I'm going the change the wiki.

**Comment by nesbox** [comment]
wiki is updated, now all is ok
```
0 - no flip
1 - horz flip
2 - vert flip
3 - horz+vert flip
```

closing on .29
