### ISSUE TITLE
Console commands for export/import spritesheets.

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#20]
It would be nice to have a console commands for importing and exporting sprite set of graphic format, such as .png

**Comment by nesbox** [comment]
will do, thanks

**Comment by nesbox** [comment]
added console commands `export sprites` and `import sprites` to save/load spritesheet from/to **.gif** file
added in .18

**Comment by Effer** [comment]
That's super convenient. Great!

**Comment by watercolorhearts** [comment]
yes this is good 
![image](https://user-images.githubusercontent.com/32391190/48800282-59971f00-ecd7-11e8-87c1-d8557c6cc14b.png)
