### ISSUE TITLE
Command line loaded sprites with wrong palette indices?

### ISSUE THREAD

**Issue by Viza74** [nesbox/tic.computer#200]
Repro:
Launch TIC
Paste a custom palette in the sprites editor
Save the tic file -> test.tic
Export sprites -> sprites.gif
Exit TIC

Launch tic with the command line tic test.tic -sprites sprites.gif
The custom palette is loaded with test.tic
The sprites are also loaded, but with using wrong colors from the palette, looking totally differently than in the gif.

Is it a bug or just I screw up something?

**Comment by nesbox** [comment]
fixed in .29
