### ISSUE TITLE
Can't save or load a cart in Windows 8.1

### ISSUE THREAD

**Issue by DDevil97** [nesbox/tic.computer#202]
When i try to load/save a cart, it outputs to the console the message "error cart loading/saving error". Also loading the demos doesn't work. I'm running it as administrator and the path to the documents folder doesn't contains any extraneous character.

**Comment by DDevil97** [comment]
Someone? Having the same problem??

**Comment by nesbox** [comment]
I'll build special build for you with additional debug info and we will try to test

**Comment by DDevil97** [comment]
Thanks, there's no hurry!

**Comment by DDevil97** [comment]
Okey, i can work around the error if i run the program as a diferent user, an idea i came up with is that the path to the appdata can't contain latin characters, in this case my user's folder contains an 'á'

**Comment by nesbox** [comment]
Added Unicode support for filesystem operations on Windows
[tic_unicode_fix.zip](https://github.com/nesbox/tic.computer/files/1123005/tic_unicode_fix.zip)
@DDevil97 pls test and let me know if all is ok
closing on .29

**Comment by DDevil97** [comment]
Works like a charm! Thanks for the amazing product and support!
