### ISSUE TITLE
Cannot change palette for new carts in config file

### ISSUE THREAD

**Issue by Tinchetsu** [nesbox/tic.computer#204]
Steps to reproduce:
Open config file.
Change default palette, for example "PALETTE = EDG16"
save the config and create a new cart with the "new" command
The result is that the new cart still have the DB16 palette.

**Comment by Viza74** [comment]
I think that's probably deprecated in 0.27 https://github.com/nesbox/tic.computer/wiki/palette
At least the "--pal" option in the metadata is deprecated, and that used those palettes stored in the config file, so I guess those values are not used any more?
But I could be completely wrong about this, I never tried to use the config file to change the palette.

**Comment by Tinchetsu** [comment]
It's a bug. Nesbox asked to open an issue for this: https://itch.io/t/96194/palette-change-from-config-file-doesnt-works-anymore

**Comment by nesbox** [comment]
you define default palette for new carts in the _config_
it's a bug

**Comment by nesbox** [comment]
fixed in .29
