### ISSUE TITLE
In browser, on AZERTY keyboards, bindings are not based on position.

### ISSUE THREAD

**Issue by Marcuss2** [nesbox/tic.computer#211]
Based on reports of one of AZERTY users, apparently it works fine in native, but not in browser.

**Comment by darkhog** [comment]
Be advised that it may be not possible to fix as it depends mostly on how browsers handle input. Try using keymap command in browser to set it up, then save config and refresh to see if it'll remain.

**Comment by nesbox** [comment]
unfortunately, it's SDL issue
