### ISSUE TITLE
JavaScript support

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#213]
made an experimental build with JavaScript support
use `new js` console command to load _Hello World_ JS demo

[tic_js_support.zip](https://github.com/nesbox/tic.computer/files/1120565/tic_js_support.zip)

![js](https://user-images.githubusercontent.com/1101448/27808177-c7c29430-604e-11e7-98b0-85584f838570.gif)

**Comment by Effer** [comment]
You!  ..... Never end to surprise me! 🤘🏼

**Comment by nesbox** [comment]
MacOSX build with JS
[tic_0.28.2.dmg.zip](https://github.com/nesbox/tic.computer/files/1121421/tic_0.28.2.dmg.zip)

**Comment by nesbox** [comment]
Linux 64bit build with JS
[tic_0.28.2.tar.gz](https://github.com/nesbox/tic.computer/files/1121540/tic_0.28.2.tar.gz)

**Comment by nesbox** [comment]
info for me: fix _remap_ callback for `map` api

**Comment by nesbox** [comment]
remap works on JS
here is example
``` js
// script: js

var t=0
var x=104
var y=24
var flr=Math.floor

function TIC()
{
	cls(13)
	
	map(0,0,30,17,0,0,0,1,
		function(i,x,y)
		{
			return i?i+2*flr(t%30/10):0
		})
		
	t++
}
```

**Comment by nesbox** [comment]
added JS support
done in .29

**Comment by DjPale** [comment]
Cool - what interpreter are you using? Curious :)

**Comment by nesbox** [comment]
@DjPale using Duktape :)

**Comment by carlsmith** [comment]
Just to be clear, if we share JS based games online, are they then using the browser's JavaScript engine? In other words, do we need to stick to the subset of JS that is supported in modern browsers and Duktape?

**Comment by jahodfra** [comment]
AFAIK they use interpretation in ducktape. Just the ducktape is compiled
into js.
We should stick to this approach if we want to keep the same behavior in
browser and desktop clients.

út 4. 9. 2018 v 15:00 odesílatel Carl Smith <notifications@github.com>
napsal:

**Comment by AldieNightStar** [comment]
Hey guys, is still here js build for latest version in 2018????
