### ISSUE TITLE
Extra spaces on command line interpreted as part of file name

### ISSUE THREAD

**Issue by gardrek** [nesbox/tic.computer#215]
When a command expects a file or directory name, any extra spaces around it are interpreted as part of the name. I am not sure if this is a bug or a feature, as there seems to be no other way to address names starting or ending with a space.

For instance, when using the `load` command with a cart file name, an extra space before or after the name causes it to fail with `cart loading error`.

**Comment by nesbox** [comment]
now TIC trims input string if detects extra spaces on the start/end
done in .29
