### ISSUE TITLE
[Android] When using Hacker's Keyboard which includes full PC keyboard layout, keys for undo/redo/copy/cut/paste are non-functional

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#223]
This is especially infuriating since on mobile the top bar is so small that's makes it easy to click wrong button and do unintended action. I suggest @nesbox to download Hacker's keyboatd from google play and test against that.

Another thing is why is there any differences between mobile and desktop at all. My understanding is that Android keyboards are sending simulated key press events to the current application that are consistent with pc scancodes. So why does TIC interpret it differently on mobile?

**Comment by trelemar** [comment]
In Hacker's Keyboard settings, make sure Ctrl key is set to "Left Ctrl".

**Comment by darkhog** [comment]
Is set, no change.

**Comment by trelemar** [comment]
Working fine for me.

**Comment by darkhog** [comment]
If ctrl-x/ctrl-v/ctrl-z wirks for you on android with HK then dunno what's wrong. Are you trying it on web version instead if the one from google play?

**Comment by trelemar** [comment]
No I'm using latest version from the play store as well as latest Hacker's Keyboard. I had the same issue in the past until @nesbox told me to enable left control in the keyboard settings. By default it it's set as ignore Ctrl input.

**Comment by darkhog** [comment]
Well, I have Ctrl key code set to left ctrl and it still doesn't work.

**Comment by darkhog** [comment]
Also ctrl+s works.

**Comment by Jusstas** [comment]
OMG had the same isue but now i changed ctrl key code to left ctrl and at first is dosent worked then I tryed to press keys while holding pressed ctrl and it worked!

**Comment by nesbox** [comment]
so, it works, the problem is in Hacker's Keyboard settings
