### ISSUE TITLE
Confusing music editor

### ISSUE THREAD

**Issue by Ktar5** [nesbox/tic.computer#224]
After reading the short description in the wiki, and browsing sample projects, I still have no idea how to work the music editor, I'd really appreciate a more detailed description for it and possibly a gif showing how it works.

**Comment by Ktar5** [comment]
nvm

**Comment by Effer** [comment]
I think some doc on tracker will help lots of people. It's a good idea @Ktar5 . 
You can learn something from some music carts. But if someone would like to write some tutorial (tromino maybe?) it will really welcome.
