### ISSUE TITLE
JS: sfx() incorrectly using "note" argument

### ISSUE THREAD

**Issue by Arkia** [nesbox/tic.computer#229]
I ported the demo cart "sfx.tic" to javascript and it seems the `sfx()` doesn't work properly in javascript. When running the following program each direction plays note "C-1" and replacing them with their numeric forms causes them to all play "E-1"

```javascript
// script: js
// input:  gamepad

t=0
id=0

function TIC(){
 if(btnp(0))sfx(id,"E-4")
 else if(btnp(1))sfx(id,"E-6")
 else if(btnp(2))sfx(id,"E-7")
 else if(btnp(3))sfx(id,"E-5")
	
 cls(15)
 spr(1+(t%20)/10,102,24,1,4)
 print("PRESS ANY ARROW KEY",64,64,0)
	
 t++
}
```

**Comment by nesbox** [comment]
fixed, here is a test build
[tic_js_sfx_api_fix.zip](https://github.com/nesbox/tic.computer/files/1151079/tic_js_sfx_api_fix.zip)
closing
