### ISSUE TITLE
Crash on attempt to export

### ISSUE THREAD

**Issue by tisajokt** [nesbox/tic.computer#23]
Linux 64-bit executable, crashes silently for all of "export", "export html", and "export native" after flashing screen for save destination.

**Comment by nesbox** [comment]
Does it crash with every cartridge export or only special?
Couldn't reproduce it on my Ubuntu.

**Comment by nesbox** [comment]
I made special build with logs[tic_with_log.tar.gz](https://github.com/nesbox/tic.computer/files/737589/tic_with_log.tar.gz)
Could you please run it in terminal, reproduce the crash and send me output.
Thanks.

**Comment by tisajokt** [comment]
Crashes for every cartridge with the same log output:

TIC: initializing GTK
TIC: creating file save dialog
TIC: running file save dialog
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gdk-Message: Error reading events from display: Invalid argument

Running Fedora 25.

**Comment by tisajokt** [comment]
Just checked, operates normally with no crash on my Ubuntu.

**Comment by nesbox** [comment]
Found the error message in GTK sources https://github.com/GNOME/gtk/blob/master/gdk/wayland/gdkeventsource.c#L93
weird but it uses _exit(1) without other alternatives :(

**Comment by nesbox** [comment]
BTW, how many displays do you have?

**Comment by tisajokt** [comment]
Single display.

**Comment by nesbox** [comment]
is it still reproducible?

**Comment by trelemar** [comment]
I've never had it crash doing this. The only time tic has crashed for me is with a large amount of code in the editor then open the function list.

**Comment by tisajokt** [comment]
Nope, it seems to have been fixed now.
