### ISSUE TITLE
JS: font() produces incorrect results

### ISSUE THREAD

**Issue by Arkia** [nesbox/tic.computer#230]
Porting the demo cart "font.tic" to javascript produces odd results. Most obviously the colorkey isn't being applied correctly, but it also seems like the characters aren't positioned correctly either.

```javascript
// script: js
// input:  gamepad

cls(12)
text="The quick brown fox\njumps over the lazy dog!"

font(text,8,8,5)
font(text,8,32,5,8,8,true)
font(text,8,58,5,5,8,false,2)

function TIC(){}
```
![font-js](https://user-images.githubusercontent.com/830307/28232892-24f2470c-68c1-11e7-9461-5ab4d133c73f.png)

**Comment by digitsensitive** [comment]
Same here. Could reproduce it.

**Comment by nesbox** [comment]
I messed up with parameters, fixed in .30

here is a test build
[tic_fixed_font_api.zip](https://github.com/nesbox/tic.computer/files/1151061/tic_fixed_font_api.zip)

closing
