### ISSUE TITLE
Incorrect Lua syntax highlighting in text editor

### ISSUE THREAD

**Issue by gardrek** [nesbox/tic.computer#232]
The syntax behavior for Lua long-form comments is completely misreprestented by the highlighting. The editor incorrectly shows comments as not commented and code as commented out unless a very specific style is followed. The interpreter, however is correct, leading to some head-scratching moments where code that looks commented out is still running.

Here is an example highlighting some of the problems. No pun intended:
![incorrect_highlighting](https://user-images.githubusercontent.com/1656630/28269172-ee77da56-6ab5-11e7-8798-d093243fafd4.png)

And here is an example of correct behavior in another program:
![correct_highlighting](https://user-images.githubusercontent.com/1656630/28269171-ee758f8a-6ab5-11e7-816b-61a26aa23c30.png)

In addition to behaviors shown above, other comment syntax is ignored, such as nest-able comments using `=` equals signs inbetween the double brackets, e.g. `--[=[ --[===[ comment in a comment ]===] ]=]`.
![more_incorrect_highlighting](https://user-images.githubusercontent.com/1656630/28269475-0c7b04be-6ab7-11e7-817d-c7ccad03d825.png)

**Comment by darkhog** [comment]
Real fun begins if you try escape quotes (`\"` escape sequence).

**Comment by gardrek** [comment]
String syntax highlighting is broken also, which makes sense, since long-form comments actually share syntax with long-form strings. Long-form strings are simply ignored, causing a variety of issues, and regular strings are broken in other ways, as hinted at by darkhog's comment.

![image](https://user-images.githubusercontent.com/1656630/29148541-bddf9952-7d33-11e7-866f-fa35d9085c84.png)
The rest of the file is highlighted as if there's an open string.
This bug only occurs if there is an even number of single quote characters _anywhere in the file_ before the end of string.
![image](https://user-images.githubusercontent.com/1656630/29148560-d8556366-7d33-11e7-8ed6-a1b09485304e.png)

**Comment by nesbox** [comment]
fixed comments
![image](https://user-images.githubusercontent.com/1101448/30481108-a0190958-9a25-11e7-841d-2b3c9e2d4206.png)

and shot quotes
![image](https://user-images.githubusercontent.com/1101448/30481150-cf1d7b9e-9a25-11e7-91aa-8932ed3cb1bf.png)

**Comment by gardrek** [comment]
This bug was closed, but a number of the issues talked about here have not been resolved. I don't know whether new bugs should be filed, or this should be re-opened, or what.

The bugs are all closely related. The biggest problems are multi-line strings being completely ignored, and multi-line comments not being able to use the `[=[` syntax, which is part of the multi-line string syntax as well. In fact, a multi-line comment is actually just a multi-line string with a comment character before it.

[This link shows how multi-line strings work, and multi-line comments are the same.](http://lua-users.org/wiki/StringsTutorial)
