### ISSUE TITLE
Export native not working in 0.29.3

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#233]
`export native` is not working anymore in version 0.29.3. `export html` works correctly.
Version 0.29.2 works as expected also. Win10.

![image](https://user-images.githubusercontent.com/1007007/28287545-65074e5a-6b3c-11e7-8243-78a59b559492.png)

**Comment by nesbox** [comment]
also `folder` command doesn't work

**Comment by nesbox** [comment]
fixed in .30
