### ISSUE TITLE
DIR console command

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#24]
Good day! I saw that the DIR console command does not work in the local version of Win XP. Reports: file system is empty try to use ADD command. Although the files are located in the working directory C:\Documents and Settings\cito1\Application Data\TIC - tiny computer\0.16.0 dev

**Comment by nesbox** [comment]
Fixed, please check it [tic_fixed_dir.zip](https://github.com/nesbox/tic.computer/files/738749/tic_fixed_dir.zip)

**Comment by KochkinBochkin** [comment]
It's worked well. Thank You!
