### ISSUE TITLE
Network commands

### ISSUE THREAD

**Issue by harbichidian** [nesbox/tic.computer#243]
It would be great if there were commands in the API for sending data via network connections to other TICs, to support multiplayer and other purposes.

Maybe the following commands:
- **`netopen(ip) -> connection`** - Opens a network connection to the given IPv4 address. Returns a `connection` object.
- **`netset(connection, data) -> nil`** - Sets the data available to the TIC on the other end of the `connection`.
- **`netget(connection) -> data`** - Gets the data (set by `netset`) from the TIC on the other end of the `connection`. If no data has been set, or no data is waiting to be read, returns `nil`.
- **`netclose(connection) -> nil`** - Closes the network connection of the `connection`.

**Comment by darkhog** [comment]
I think this would be too much. What I would want to see, however is a netplay feature (as seen in certain NES emulators) that allows a remote player to join in and man the second controller.

**Comment by Jusstas** [comment]
We need this

**Comment by DjPale** [comment]
Out of scope for a FC IMHO. If you find yourself needing these kinds of functions, you should probably use a game engine.

**Comment by nesbox** [comment]
agreed, Out of scope for a FC
closing...

**Comment by msx80** [comment]
I know that you already declared a network api to be out of scope, but i think there's interest in it and will be requested often. I'd like to propose a simpler api based on two functions:

*bool connect(address)* - connects to the address and return wethere the connection was established (any preexisting connection will be closed).

*string transmit(string)* - both sends the data passed as parameter and returns any pending data. Strings in lua are really byte buffers so pretty flexyble for both binary and text based protocols. Empty strings would mean no data to send/receive, nil would mean close the connection (if sent)/the connection was closed remotely (if received).

It could eventually be built on top of websockets for the following advantages:
- possible (and easy) implementation in html
- deep linking (ie passing data along with the connection, like ws://myserver?data=mycustomdata)
- sent buffers are always received as whole, never splitted or merged with previous or next data

Beside games, it could be used for many other things.. I'd love to see a BBS for TIC to relive the days of C64 bbs :)

No problem if you still think it's out of scope, just wanted to share my 2 cents

**Comment by jahodfra** [comment]
I think websockets are based over TCP/IP so it will be probably slow for realtime games (Each packet has to be confirmed). On the other hand it can be fine for everything else.
