### ISSUE TITLE
Map editor: Ability to put flipped sprite into a map cell

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#244]
TIC-80 has flip functions for sprites, which is nice, however it's not possible to set "flipped" flag for the map tile. Which means that even if you have perfectly symmetrical object, you still waste few sprite slots just to store "flipped" version of the sprite for map use only. Thrones, double doors and so on can all be examples of such objects. This means you can pack way less graphics into your game that you could if the map data had flags for whether or not sprite is flipped horizontally/vertically on a per map cell basis.

**Comment by trelemar** [comment]
Check out the remap call back function withing the map function. You can flip, rotate, or even completely change the tile while doing the map draw call. TIC stores the map cells in the RAM, so having an additional flip flag would require more RAM and I'm pretty sure nesbox doesn't plan on changing it. The remap function is perfect for doing exactly that. As for "wasting" sprite space, working within the limitions is what TIC is all about.

**Comment by nesbox** [comment]
yes, I'm not going to add additional states to the map tiles, pls use `remap` api
closing
