### ISSUE TITLE
Music editor: Row indicator

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#248]
It would be nice if we had a way to tell which row in currently edited pattern we're at. Cuurently I have to count by hand what row I'm at, which if I, for example, am transcribing music from a module file to Tic, is a real chore.

**Comment by nesbox** [comment]
![image](https://user-images.githubusercontent.com/1101448/28678572-64c9b13e-72f9-11e7-9f90-114546a93b73.png)
done in .30
