### ISSUE TITLE
Map Editor (0.30.0): Fill in selected box only (Suggestion)

### ISSUE THREAD

**Issue by nickifr** [nesbox/tic.computer#249]
When using the new map editor in 0.30.0, I noticed the following rather unintuitive behaviour when trying to use the fill tool inside a selected box:

When you use the fill tool inside this selected box, it should only fill the area you selected:
![screenshot 1101](https://user-images.githubusercontent.com/22664233/28665189-265a2f22-72c3-11e7-948a-7c6f6ab46f14.png)

However, the current effect is this:
![screenshot 1102](https://user-images.githubusercontent.com/22664233/28665229-4dd571b0-72c3-11e7-8f06-bb18b8e2aae3.png)

The intuitive effect (as used in multiple other applications, like Paint.NET or Gimp) would be this:
![screenshot 1103](https://user-images.githubusercontent.com/22664233/28665323-95246b7a-72c3-11e7-8abd-9891ed9eab4b.png)

**Comment by darkhog** [comment]
Agreed. It would be very useful.

**Comment by nesbox** [comment]
done in .30
