### ISSUE TITLE
 The moonscript does not run if you run it with the command dofile('game.lua')

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#25]
Lua script works without problems.
Moonscript example, which certainly works in the editor:

--[moonscript]

export TIC=->
	cls 8
	print "sum: "..sum(10,20)
	
export sum=(x,y)->x+y

**Comment by nesbox** [comment]
ok, seems I have to override **dofile** LUA function

**Comment by nesbox** [comment]
fixed in 0.17.0
