### ISSUE TITLE
sfx() should intelligently chose an empty channel if none is provided

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#251]
As it is now, if music plays and channel 0 is occupied, it simply pauses/unpauses that channel to play sound effect (like it did on atari 2600 for the few games that had both music and sfx) even if there are empty (unused) channels available. This should be chqanged so if music/other effects are playing and there is unoccupied channel available it would intelligently use it to play effect in tandem with what is currently playing. It should only resort to pausing/unpausing channel 0 if no empty channel is available (all 4 channels are currently in use).

**Comment by nesbox** [comment]
honestly, I don't want to complicate SFX playing logic, but you can select empty channel before playing SFX by `peek` sound register freq/volume, if it empty just call `sfx()` on this channel
