### ISSUE TITLE
Moonscript not finding TIC function

### ISSUE THREAD

**Issue by arthurferrai** [nesbox/tic.computer#255]
Running given code:
![ss1](https://user-images.githubusercontent.com/5352649/28827342-a86ea676-76a3-11e7-8cd7-21ca93bb62eb.png)

gives me the error:
![ss2](https://user-images.githubusercontent.com/5352649/28827352-b0fe98dc-76a3-11e7-9adb-a78806a5cf63.png)

However an inline loop works as expected:
![work1](https://user-images.githubusercontent.com/5352649/28827440-f6c1dfe6-76a3-11e7-8511-7ba7dd4d77b5.png)

gives the expected result (after pressing Esc):
![work2](https://user-images.githubusercontent.com/5352649/28827455-ff89fa46-76a3-11e7-9f08-6128323d07b7.png)

**Comment by nesbox** [comment]
hmm, it's weird...
try to enter `new moon` command in the console and `run` then

**Comment by arthurferrai** [comment]
Running `new moon` and then `run` works as expected.

**Comment by nesbox** [comment]
Ok, could you pls save and attach to issue .tic cartridge which doesn't work

**Comment by arthurferrai** [comment]
Attached .tic file:
[test.zip](https://github.com/nesbox/tic.computer/files/1191330/test.zip)

Ok, I think I found the problem: when I enter a new line, code editor auto-indent code using a `Tab` character. Since Moonscript threats tabs as 4 spaces, it confuses the interpreter (it should fail to parse code, and maybe that's why it can't find TIC function). I think a more descriptive error here would be good, as well as replace `tab` to `space` character (since it's only one space after all).

**Comment by nesbox** [comment]
so, I found a workaround:
- go to `config`
- go to Sprite Editor and create your symbol for TAB character, like this
![image](https://user-images.githubusercontent.com/1101448/30480337-f467711a-9a21-11e7-8f11-15d5b56f20b0.png)

- save config
 and now you'll see all the tabs in the script
![image](https://user-images.githubusercontent.com/1101448/30480364-0b697304-9a22-11e7-8baa-f699f3e0f48c.png)

closing...

**Comment by arthurferrai** [comment]
Thanks, that's a pretty good workaround :D

**Comment by sergsoares** [comment]
You're awesome, fix for me too.

Thanks a lot.
