### ISSUE TITLE
Native export does nothing on Windows 10 when launched from cmd-line

### ISSUE THREAD

**Issue by DjPale** [nesbox/tic.computer#267]
Native export using `export native` doesn't produce anything and gives no messages. When trying to execute and pressing <Enter> it also doesn't do a proper carriage return.

![image](https://user-images.githubusercontent.com/1427902/29342921-ffddc1e0-822d-11e7-95fc-d2fed8403ffb.png)

**Comment by nesbox** [comment]
does it reproduce on every cartridge or only specific?

**Comment by DjPale** [comment]
Update: Applies to all carts - but in this case I was launching `tic.exe` manually through command line. When I launched it from the itch client it worked OK. I think I have found the problem:

![image](https://user-images.githubusercontent.com/1427902/29367552-8ccf8f88-829d-11e7-9aa7-edf1307a8024.png)

Suggested fixes:
* Handle error more gracefully
* Create directory if missing

**Comment by nesbox** [comment]
fixed in .40
