### ISSUE TITLE
What if I want to make big multiplayer game?

### ISSUE THREAD

**Issue by Winterwolf** [nesbox/tic.computer#27]
Hello, Vadim. Your project is *awesome*! I fell in love at first sight, thank you very much for your work! :3

I actually have a question - what if I want to make something more than little 64k game? I want to make online game with udp-server. Can you add socket support and remove 64k limit? It is possible theoretically?

**Comment by nesbox** [comment]
Hi, 
thanks for appreciation

I can add socket support to the API I think, but I'm not sure about removing 64K code limit because TIC is a tiny computer designed to make tiny games :)

**Comment by Winterwolf** [comment]
Speaking of big games... I just studied the code of the built-in game quest.tic and noticed that the code editor working very slow when I trying to type something. Amount of code is too big for him. Seems it is a bug :(

**Comment by nesbox** [comment]
yes, already have the bug in my internal tasks list, will fix it
TIC hasn't released yet and it's in development status

**Comment by Winterwolf** [comment]
Well, thank you, I wish you success! Add sockets please in the future, if not difficult.

**Comment by nesbox** [comment]
Thanks.
Create a new socket issue here please.
