### ISSUE TITLE
Game menu

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#270]
show Game Menu for exported and website games
by pressing ESC or BACK on mobile

![menu](https://user-images.githubusercontent.com/1101448/29619282-67d6f758-8823-11e7-9299-46d92d00cd47.gif)

**Comment by trelemar** [comment]
If I could like this 1000 times I would! 😁

_Sent from my HONOR FRD-L04 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AlRado** [comment]
Very usefull!

**Comment by nesbox** [comment]
done in .40

**Comment by FayneAldan** [comment]
"or BACK on mobile"
Wait, you can export to mobile?

**Comment by nesbox** [comment]
@FayneAldan not yet, but I'm going to add it
also, you can upload your game to https://tic.computer website and load it from the TICs console ([tic.computer/play] directory)
