### ISSUE TITLE
TextEditor

### ISSUE THREAD

**Issue by MaxPlay-BR** [nesbox/tic.computer#271]
Hello How Can I Edit The Code Of The Game With An External Editor On Android?

_Sent from my Motorola XT1069 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nesbox** [comment]
add `dofile("/path/to/your/script.lua")` to the first line in the Code Editor
and open `script.lua` in an external editor
https://github.com/nesbox/tic.computer/wiki#using-external-code-editors

closing...
