### ISSUE TITLE
Android app full screen

### ISSUE THREAD

**Issue by Azn9** [nesbox/tic.computer#272]
Hi, on my smartphone, the app isn't on full screen, as you can see here: https://img15.hostingpics.net/pics/494032Screenshot20170825122812.png

Si can you make the app to be in full screen please?

Thanks,
Azn9

**Comment by trelemar** [comment]
Hi Azn9, What you're seeing is the result of different screen aspect ratios, and pixel interger scaling. TIC-80 will scale it's screen dimensions the larger possible for your screen. If it took up the entire screen, it would have to distort the display, resulting in pixels that would appear larger than others, so the border helps keep everything looking correctly. Here's an example of what happens:

![Font scaling](http://vignette3.wikia.nocookie.net/emulation-general/images/f/fb/Integer_scaling.png/revision/latest?cb=20130715154216)


_Sent from my HONOR FRD-L04 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
