### ISSUE TITLE
[0.40.0] "export native" doesn't export .dll's (Windows)

### ISSUE THREAD

**Issue by nickifr** [nesbox/tic.computer#273]
When exporting a game on Windows in 0.40.0 (Pre-Release), the native .dll's are not exported automatically. This results in the user having to manually copy and paste the .dll's from the original TIC-80 download next to the executable to get it to work.
![nativeexportdllsmissing](https://user-images.githubusercontent.com/22664233/29715906-97c69bd0-89a9-11e7-988e-7a1cf56ba022.png)

**Comment by nesbox** [comment]
yes, I should copy dlls too

**Comment by nesbox** [comment]
added _Browse for Folder_ dialog to save all the game files

done on .40
