### ISSUE TITLE
[0.40.0] "config" doesn't work when in a subdirectory

### ISSUE THREAD

**Issue by nickifr** [nesbox/tic.computer#274]
If you are not in the main save directory (but instead you are in a subdirectory), you can't access the config. Instead "config" raises a cart loading error. This did work in version 0.30.0.
![configfromsubdirectory](https://user-images.githubusercontent.com/22664233/29726483-30388b64-89d0-11e7-8218-c7ee49e7cf2b.png)

**Comment by nesbox** [comment]
fixed in .40
