### ISSUE TITLE
[macOS] Input metatag set to mouse gives an error

### ISSUE THREAD

**Issue by mar-sw** [nesbox/tic.computer#275]
![screen1](https://user-images.githubusercontent.com/31326866/29734089-b161cdae-89c6-11e7-9100-0fd041587f62.png)
![screen2](https://user-images.githubusercontent.com/31326866/29734090-b1f46a60-89c6-11e7-9e9e-a9b1336df79a.png)

**Comment by mar-sw** [comment]
Edited because in 0.30.0 also happens.

**Comment by nickifr** [comment]
This is how it's supposed to work, you can't use "[btn()](https://github.com/nesbox/tic.computer/wiki/btn)" when using mouse input. You're instead supposed to use "[mouse()](https://github.com/nesbox/tic.computer/wiki/mouse)".

**Comment by mar-sw** [comment]
Oh, my mistake :P
