### ISSUE TITLE
Ability to edit default game template in similar way to config

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#276]
The "config as a cartridge" option inspired me to make this suggestion. How about adding the ability to edit default game template (one that you use with new command) in similar way?

**Comment by nesbox** [comment]
Why don't you want to create `empty.tic` cartridge and load it as default template?

**Comment by darkhog** [comment]
Because then I may accidentally overwrite it with ctrl+s.

**Comment by nesbox** [comment]
added new params to the `config` command
`config default` or `config default lua` - loads default template for the new LUA cart
`config default moon` or `config default moonscript` - loads default template for the new Moonscript cart
`config default js` - loads default template for the new JS cart

done in .41
