### ISSUE TITLE
Alt-1 adds "1" to the editor

### ISSUE THREAD

**Issue by benob** [nesbox/tic.computer#277]
When pressing Alt-1 to switch to the editor, it adds the character "1" to where the cursor is, modifying the code.

**Comment by nesbox** [comment]
Can't reproduce on Win and Html version.
What system do you use?

**Comment by benob** [comment]
Linux x64 (tried v0.30 and v0.40). Elementary OS (Ubuntu 16.04 based).

**Comment by nesbox** [comment]
fixed in .40
