### ISSUE TITLE
time() function returns different values depending on how the program is run

### ISSUE THREAD

**Issue by Mimerme** [nesbox/tic.computer#278]
If you exit the program with ESC then press ctrl+r, then the time() becomes a number between 15-20 (on my computer) on the first TIC. But if you press ctrl+r while the application is already running to restart it, then time() becomes <1.

**Reproducing**
`cls();
print(time());
`
1) Exit to the console using ESC
2) Run the program with CTRL+R
3) Note the value
4) Run again with CTRL+R
5) Value is completely different

To me, it looks like the first value is a mistake

**Comment by nesbox** [comment]
now `time()` returns < 1 in all cases
fixed in .41
