### ISSUE TITLE
Changelog hasn't been updated since 0.28.0

### ISSUE THREAD

**Issue by idontfucking** [nesbox/tic.computer#281]
but seriously why isnt it open. also transparency with spr() doesnt work for some reason after I changed the rgb of a color in the palette.

**Comment by nesbox** [comment]
changelog is here now https://github.com/nesbox/tic.computer/releases
as for transparency with `spr()`, I'll try to investigate
Thanks

**Comment by nesbox** [comment]
hmm, can't get bug with `spr` transparency
could you pls provide your code
thanks
