### ISSUE TITLE
Game menu wraps downwards but not upwards

### ISSUE THREAD

**Issue by nmmarzano** [nesbox/tic.computer#286]
Open the menu in-game, if you keep pressing down you'll find that once you're on the bottom option and press down it wraps back up to the top option and you can keep going like that
  On the other hand, pressing up while you're on the top option doesn't wrap around to the bottom

  Not sure which of the two is the intended way but the inconsistence made it look like a bug or oversight

**Comment by nesbox** [comment]
fixed, now it wraps downwards and upwards
closing...
