### ISSUE TITLE
Can't upload a TIC file to the website

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/tic.computer#288]
[zolatunewip.zip](https://github.com/nesbox/tic.computer/files/1285105/zolatunewip.zip)
"Please add at least TITLE, AUTHOR and COVER (by press F7) metadata to the cartridge and try again."

I did add the "Cover" metadata tag inside the cartridge, but it doesn't want to be uploaded on the site! What am I doing wrong?

**Comment by nesbox** [comment]
Seems you pressed F7 to assign cover and haven't saved it.
I looked into your cartridge and it doesn't have cover.
closing...

**Comment by StinkerB06** [comment]
Oh gosh. Tried and still nothing
[zolatunewip.zip](https://github.com/nesbox/tic.computer/files/1286354/zolatunewip.zip)

**Comment by nesbox** [comment]
still nothing
![image](https://user-images.githubusercontent.com/1101448/30196389-f5631808-9468-11e7-81eb-27e998aca3e0.png)

**Comment by StinkerB06** [comment]
Thanks! Check the cartridge out on the website! https://tic.computer/play?cart=203
