### ISSUE TITLE
Into the web version does not work copy / paste from other programs, such as the text editor, for example.

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#29]

**Comment by nesbox** [comment]
unfortunately TIC doesn't have access to system clipboard in HTML5 version for security reason
it's browser restrictions
http://stackoverflow.com/questions/22366123/emscripten-copy-paste-clipboard
and it couldn't be fixed, closing

**Comment by AlRado** [comment]
It's not scary, because I can download the cartridge using the 'get' command.
