### ISSUE TITLE
Two things

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/tic.computer#292]
1. I would like to know every other register bits in the 80K RAM (you showed us the sound PSG so far)
2. The cartridge names on the website are all in uppercase, which makes it difficult to load a game from the site by running TIC-80 and changing the directory to "tic.computer/play". I recommend showing both uppercase and lowercase.

**Comment by nesbox** [comment]
1. try to look into https://tic.computer/play?cart=166 and https://gist.github.com/nesbox/df637a2f91efc981f25f923af0bc10aa
2. you can use SURF mode in .41 and load carts from UI

closing...

**Comment by StinkerB06** [comment]
1. I meant to show every bit in the 80kB memory layout. Learn American English some time.
2. There's a more recent version of TIC coming by now?
