### ISSUE TITLE
Implement SURF mode

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#293]
to browse local and website cartridges

**Comment by nesbox** [comment]
I'm not realized how to show covers for now, so I just implemented very simple version of the Surf
Only browsing and loading games

![surf](https://user-images.githubusercontent.com/1101448/30391451-0d1429e4-98c2-11e7-9f35-c976467fdc20.gif)

other features will be added later

**Comment by trelemar** [comment]
This serves a great purpose even without covers. Will Android touch buttons be usable in this mode?

**Comment by nesbox** [comment]
@trelemar yes it works with any gamepad input, touch or real, 
also, SURF will automatically load if you press any gamepad button in the console (useful if you don't have keyboard and mouse, on XBox for example)

**Comment by Effer** [comment]
What about ping pong the cover? Scrolling it inside a clipped window?
(It's awesome BTW)

**Comment by nesbox** [comment]
@Effer I tried to draw 1/2x scaled covers at the right, but they look ugly, don't know

![surf-image](https://user-images.githubusercontent.com/1101448/30414531-b9ee5602-992c-11e7-9afb-0fa2148af202.gif)

**Comment by AlRado** [comment]
Can be added to the cartridge the second cover - a small one, and if it is not specified, then display the main one in a reduced form?

**Comment by nesbox** [comment]
Another way to draw covers, but cartridge names become unreadable

![surf-image](https://user-images.githubusercontent.com/1101448/30417368-2253f2c8-9938-11e7-8e29-650b29917840.gif)

**Comment by AlRado** [comment]
Сan be like this?
![2017-09-14_10-37-14_](https://user-images.githubusercontent.com/440703/30418623-46a7d78a-993c-11e7-80b9-88d0beae27db.png)

**Comment by nesbox** [comment]
OK, added some kind of transparent background for the names to make it visible

![surf](https://user-images.githubusercontent.com/1101448/30420671-ff6ea4d2-9942-11e7-83d9-4be0717d0cdd.gif)

**Comment by Effer** [comment]
@nesbox , honestly they all seems... let's say: not perfect? .
Can you try to show the cover in the window without scaling? Then apply some scrolling movement to the image.  You'll see only a portion of the cover at 1:1 but moving it around will show all the image.
Not sure I've been clear, maybe I could try to draft something tonight.

**Comment by nesbox** [comment]
@Effer how about this one?
![surf](https://user-images.githubusercontent.com/1101448/30429888-d750f936-9961-11e7-8efc-09aa432e010b.gif)

**Comment by trelemar** [comment]
@nesbox This one! :grinning:

**Comment by nesbox** [comment]
a bigger preview window

![surf](https://user-images.githubusercontent.com/1101448/30431129-4e5cea18-9966-11e7-9ed5-de99fbef3012.gif)

**Comment by Effer** [comment]
Yes! That's what's I mean! 
Minor thing to try: start with a diagonal movement and let it bounce on hitting border,maybe a little faster. (classic reverse dx and dy)

**Comment by nesbox** [comment]
yes, I made bouncing here https://github.com/nesbox/tic.computer/issues/293#issuecomment-329467613

**Comment by Effer** [comment]
ops missed. That with the bigger window for me.

**Comment by nesbox** [comment]
@Effer look at this
![surf](https://user-images.githubusercontent.com/1101448/30440392-0ce9e6c6-997f-11e7-897f-84064985632b.gif)

**Comment by nesbox** [comment]
![screen](https://user-images.githubusercontent.com/1101448/30471889-0fefef94-9a03-11e7-90c3-c229eb643e0d.gif)

so, I implemented SURF with fullscreen covers preview on BG
maybe will add more modes in next versions
closing...
