### ISSUE TITLE
SURF return to TIC doesn't restore previous line index (and other suggestion)

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#296]
- It would be nice to restore cursor to last selected entry when exiting from a cart.
- Also It would be nice to make the menu scroll continuous: from last entry press down bring back to top entry (and viceversa also ;)
- And last but not last: use a button to open tic.computer page for selected entry (online only) with system browser. In this way people can comment and vote.

**Comment by nesbox** [comment]
ok, great idea with the website 👍

**Comment by trelemar** [comment]
In addition to launching the webpage for the game, if we could sort by newest instead of most popular would be another great feature.

**Comment by nesbox** [comment]
- cursor restores when you back from a game
- menu scrolls continuously
- press [Y] to open website cart page

![image](https://user-images.githubusercontent.com/1101448/30546644-e1cb4ce0-9c95-11e7-9ed8-430589611f5f.png)

- popular/new soring will be a separate issue...
