### ISSUE TITLE
(0.45.0) Can't save website carts from SURF

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/tic.computer#298]
![bandicam 2017-09-17 13-49-55-311](https://user-images.githubusercontent.com/30059831/30524803-796194d4-9baf-11e7-8b0e-41cc637829f6.jpg)

**Comment by trelemar** [comment]
You need to navigate to a local directory to save the cart. You cannot override a tic.computer cart. 
Try `cd /` then try saving

**Comment by StinkerB06** [comment]
Thanks!
![bandicam 2017-09-17 16-05-07-248](https://user-images.githubusercontent.com/30059831/30525782-2a5d3664-9bc2-11e7-89a1-538023f2b57b.jpg)
