### ISSUE TITLE
Camera operator

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#31]
Maybe implemented camera operator for a smooth scrolling like as PICO-8?. If the camera operator is not specified in the user program(script), use the only map operator for backward compatibility.

**Comment by nesbox** [comment]
**camera** method sets offset for all drawing operations in pico8 and you can use **map** api in TIC to make smooth scrolling
so, I'm not sure because you can do all these things with the current API

**Comment by KochkinBochkin** [comment]
Thank you, it worked, I tried to use additional parameters in MAP method.

**Comment by nesbox** [comment]
great :)

**Comment by Effer** [comment]
**camera** could be useful when you need to _shake_ the full screen, both background and player/enemy sprites I mean. But I'm not sure if it fit well with the current API. What happen at the map borders?

**Comment by nesbox** [comment]
@Effer you're right it could be useful for screen shaking and it will fit current API without problems.
If you worry about unpainted map borders during shaking just draw map with bigger area to avoid it.

**Comment by nesbox** [comment]
new task: 
add camera [x y] api

**Comment by Effer** [comment]
I'll do, but have the map editor fit exactly one screen for section was so cute.
I'll make a border, or something like that.

**Comment by nesbox** [comment]
I have an idea about CAMERA function, what if we'll shake entire screen buffer, it will save us from the 'map border' problem. Also it will be better for performance (we don't need to calculate offset on every draw operation)

**Comment by Effer** [comment]
So is how I thought you'd done.  You could also zoom in/out. But that will be a little too much.. is't it?

**Comment by nesbox** [comment]
zooming is a bit much I think :)
And we should give it another name, maybe 'shake [x y]'

**Comment by Effer** [comment]
Totally agree.

**Comment by nesbox** [comment]
created new issue https://github.com/nesbox/tic.computer/issues/33
close then
