### ISSUE TITLE
Moonscript: dynamic code preview does not display the names of methods

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#32]
![2017-02-01_07-57-33](https://cloud.githubusercontent.com/assets/440703/22495745/a8b3cfe0-e854-11e6-8402-0e26c88b4aea.png)

![2017-02-01_07-55-57](https://cloud.githubusercontent.com/assets/440703/22495735/7745a848-e854-11e6-8fdd-22eba9f53808.png)

**Comment by nesbox** [comment]
added moon function to the _code outline_
displays only moon functions, not class methods

![moon](https://cloud.githubusercontent.com/assets/1101448/23372704/c9cbb646-fd2d-11e6-84d2-2da75cf6c72c.gif)


closing on .19
