### ISSUE TITLE
shake screen API function

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#33]
add a function to draw entire screen buffer with XY offset
`shake [x y]`
the offset will reset every frame to 0:0 if you won't call the shake api

**Comment by nesbox** [comment]
I decided not to add 'shake' API func and added XY variables to the RAM by address 0x3FF9

![shake](https://cloud.githubusercontent.com/assets/1101448/22551354/8f23410c-e965-11e6-9a2d-93a8826edfab.gif)

```lua
-- 'shake screen demo' demo

shake=0
d=4

function TIC()

	if btnp(4) then shake=30 end

	if shake>0 then
		poke(0x3FF9,math.random(-d,d))
		poke(0x3FF9+1,math.random(-d,d))
		shake=shake-1
		
		if shake==0 then memset(0x3FF9,0,2) end
	end

	cls(12)
	print("PRESS ANY KEY TO SHAKE THE SCREEN!",24,64)
end
```

so, works in .17

**Comment by AlecTroemel** [comment]
I know this is really old, but in case anyone wants to do this in javascript, its Math.random works a little bit differently. To get a random number between min and max (what lua's random does), you could do something like 
```javascript
var min = -d, max = d
Math.random() * (max - min) + min
```
