### ISSUE TITLE
Can't save clean cart

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#34]
It's a bit odd but here how to reproduce it:
- make a new cart
- save with a name
- -->can't save

Open the code editor write just one char (or more), now you can save. It seems like the modification can come from any editor.

What about if the NEW cart will contain at least the TIC function definition? At the end TIC function is strictly required.

**Comment by nesbox** [comment]
ok, will add TIC function definition by default

**Comment by nesbox** [comment]
fixed in .17
