### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by Pyr0Byt3** [nesbox/tic.computer#36]
Would it be possible to add an API function for polling mouse coords and buttons? Or maybe a memory location one could use to peek() the mouse data?

**Comment by Pyr0Byt3** [comment]
Well, for what it's worth, [here's how PICO-8 does it](http://pico-8.wikia.com/wiki/Stat#Devkit_mouse_mode). TIC has no stat() function, so the same method wouldn't really work... But maybe it'll give a few ideas?

**Comment by nesbox** [comment]
Here are my thoughts

I'm going to add cart metadata editor where you can define title, author, cover...
And also you will be able to define input method for the game: gamepad or mouse.

So, gamepad state takes 16 bit (8bit+8bit for two players) in memory.
We have 240*136=32640 pixels, it will take 15 bit to address mouse pointer/finger position and 1 bit for button/touch state (pressed/unpressed) to fit the same memory.

    +-----------+-----------+
    | gamepad 1 | gamepad 2 |
    +-----------+-----------+
    |   8 bit   |   8 bit   |
    +-----------+----+------+
    | mouse position |  btn |
    +----------------+------+
    |     15 bit     | 1bit |
    +----------------+------+

**Comment by Pyr0Byt3** [comment]
Yeah, that seems fair. I was thinking right-click would be nice, but I don't see how it would fit in 16 bits, and it would make dealing with touchscreens difficult... So I'm happy with the 1-button compromise :)

**Comment by nesbox** [comment]
ok, will implement this #37 before

**Comment by Effer** [comment]
So no mouse+keyboard? I am rather fought between your clean approach and the confort of a very common way of control.

**Comment by nesbox** [comment]
I thinks yes, I want to all the TIC games be playable on mobile devices where you can't use both gamepad+mouse.

**Comment by Effer** [comment]
That make sense. I think I can live with it :)

**Comment by nesbox** [comment]
Added mouse support

![mouse](https://cloud.githubusercontent.com/assets/1101448/22622228/fb030d4e-eb45-11e6-8652-b69afc83f5d5.gif)

Can't decide add **mouse** api function or let people calculate mouse XY by themselves like in example?

```lua
-- title:  mouse
-- author: nesbox
-- script: lua
-- input:  mouse

function mouse()
	local b=btn()return(b&0x7fff)%240,(b&0x7fff)//240,b>>15
end

function TIC()

	cls(12)

	local x,y,down=mouse()
	
	spr(1+down,x-16,y-16,-1,4)
	print("x="..x.." y="..y.." btn="..down)
end
```

**Comment by Pyr0Byt3** [comment]
API function, I think... That way, it would be consistent with gamepad input, which has btn() and btnp().

**Comment by Effer** [comment]
I'm a lazy man... **mouse** is welcome

**Comment by nesbox** [comment]
done in .18
