### ISSUE TITLE
Cartridge metadata editor

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#37]
add following metadata to cart:
1. title
1. author
1. description
1. tags
1. input method (gamepad/mouse)
1. ...

and implement method to edit meta info

**Comment by nesbox** [comment]
added cartridge metadata like in example below:

``` lua
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua (or moonscript)
-- input:  gamepad (or mouse)

function TIC()
	cls()
	print("HELLO WORLD!")
end
```

to enable Moonscript use `-- script: moonscript` tag

**Comment by Effer** [comment]
What about add also the palette? In a way similar to the config file?

**Comment by nesbox** [comment]
@Effer will do, pls create separate issue. thanks
