### ISSUE TITLE
Add Palette in Metadata Cartdrige

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#38]
Keeping the same format of config file will help avoid misunderstandings.
If no palette is defined use the standard one.

**Comment by trelemar** [comment]
would this also allow us to define a game specific palette? For example:
`local palette = "000000".."123456".. --ect x 14`

**Comment by trelemar** [comment]
would this also allow us to define a game specific palette? For example:
`local palette = "000000".."

**Comment by nesbox** [comment]
in `config.lua` you can define system palette and system font only.

in cartridge metadata you can define game palette which will be loaded on game startup
the syntax will be like `-- pal: db16` (to assign predefined palette) or `-- pal: 00000057420040318d5050508b542955a0498839327878788b3f967869c49f9f9f94e089b8696267b6bdbfce72ffffff` to assign your own palette

`print` api function draws only user system font, pls use `font` api to draw game specific font.
Try to load `font.tic` demo to see how to use it (it renders text directly from the foreground (FG) sprites)

**Comment by nesbox** [comment]
added `-- pal: ...` tag, if the tag not defined the system palette will be loaded
done in .18
