### ISSUE TITLE
TIC's r-w directory requires root to edit and view on Android.

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#39]
```/data/data```
Requires root permissions on Android.
```/Android/data/``` does not. It'd be nice to access my .tic without rooting my tablet or phone.

**Comment by nesbox** [comment]
I made a fix and now files are in `/Android/data/com.nesbox.tic/files`

Pls check it
[tic-fixed-folder.zip](https://github.com/nesbox/tic.computer/files/754590/tic-fixed-folder.zip)

**Comment by trelemar** [comment]
That works! Perfect!

**Comment by nesbox** [comment]
ok, fixed on .18
closing

**Comment by octoConnors** [comment]
I had an issue where my saved file was not in the specified location of /Android/data/com.nesbox.tic/files

I had an older .tic file which was in this location, however, and I overwrote that file with my newer file and it DID save to that same file. Thus I was able to retrieve my file from /files, however I suspect my file originally saved to the hidden location...
