### ISSUE TITLE
sprites flag

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#40]
Hello,

Can you add in the sprite editor a sprite flags like pico8?

**Comment by nesbox** [comment]
There is a problem, TIC has 256 BG + 256 FG=512 sprites, so we need 512 bytes to store flags in the 64K RAM, here is the layout
```
64K RAM layout
--------------
0000-SCREEN
3FC0-PALETTE
3FF0-PALETTE MAP
3FF8-BORDER COLOR (experimental)
3FF9-SCREEN OFFSET (experimental)
3FFB-(reserved for future use)
4000-SPRITES
8000-MAP
FF80-SOUND REGISTERS
FF90-PERSISTENT MEMORY
FFD0-(reserved for future use)
```
and unfortunately there is no free space for these 512 bytes.
Don't know what to do now...

**Comment by nesbox** [comment]
As variant I can store these flags in the hidden ROM section (like SFX section or Lua Script) but you wont have access to change _flags_ in the runtime, only read. Don't like this variant 👎

**Comment by Effer** [comment]
Use one page in the MAP range.
Or buy more RAM Chip and rise to 80k :)

**Comment by AlRado** [comment]
I think you can expand the memory, if now is not enough places for features. Сan be right up to 128k?
Or is contrary to the ideology of TIC?

**Comment by nesbox** [comment]
Yes, TIC has limitations - 64K RAM only and it wont be changed.
Don't know, maybe cut the map memory for flags is a good decision, but my inner perfectionist is resisting :)

**Comment by KochkinBochkin** [comment]
It seems necessary to vote on the need flags)

**Comment by trelemar** [comment]
I mean I wouldn't want to compromise map memory just for sprite flags. Just throw all your sprite indexes of a certain flag into a table.

**Comment by Gi972** [comment]
Lol me, I think upgrade to 128k is a good solution :D , but just only 128 no more.

Don't forget at the time the screens was 4/3 not 16/9 so less ram necessary.
Briging modernity to the nostalgia :) !!

**Comment by harraps** [comment]
rather than having 8bits flags for both FG and BG, you can have 1bit flags for each BG...
¯\_(ツ)_/¯

**Comment by nesbox** [comment]
@harraps I don't know how to use 1 bit flags?

**Comment by Raidez** [comment]
Flags is useful for categorize sprite, but 1 byte is to much.
I thinking can be add for experimental (like border-color, screen offset) with 2,3 or 4 bit flags for each BG or FG.

**Comment by Effer** [comment]
So if @nesbox find a way to stole some bytes.. for BG sprites just 4 bit as flags. 128bytes.

The map allow for 64 rooms. It's a good number of levels. Each room is 30*17=510 cells. I suppose each cell is one byte (256 values, the reason you can use only the 256 BG) used as sprite index. If we sacrifice one room we have enough memory for that flags. Also if one don't use the memory the room will stay clean.

Also It could be nice to have a way to flag as rotate/flip the sprite in the map.  But for that it'll take something like 4 bit (2 flip and 2 Rotate) stealing really too much memory.

Maybe allow the user to allocate memory and map as prefer. In this way one could sacrifice one rooms to have the flags and more rooms to allow the sprites to be flipped/rotate in the map editor. The tools will be far more complex.

That said, when in need to mark sprites, using a table in the code is not so difficult.

**Comment by nesbox** [comment]
I have one more idea, what if I add a _filter_ callback parameter to the _map_ api
`map cx cy cw ch [ x y [colorkey [filter]]]`
and you will able to decide to show tile on rendering or not
```lua
-- draw map with all the tiles except with id==15
map(0, 0, 30, 17, 0, 0, -1, function(id,x,y) return it~=15 end)
```

**Comment by Effer** [comment]
Does the function call back really help? I mean is not so different to check it in code. Probably most users would prefer a GUI way to adjust map. Not so easy to fit all needs.

**Comment by nesbox** [comment]
@Effer yes, perhaps the callback is unnecessary because user can always draw a map by himself and decide to show a sprite or not

**Comment by nesbox** [comment]
So, TIC doesn't have enough memory to store tile/sprite flags but you can store flag values in a LUA table

```lua
FLAGS={}
function fset(i,f)
  local val=FLAGS[i] or 0
  FLAGS[i]=val|(1<<f)
end

function fget(i,f)
  return FLAGS[i]&(1<<f)
end
```

also I added `remap` parameter to map api which will help to show/hide on map rendering stage (also, you can remap tile index to make map animation or even flip/rotate)

> `map [cellx celly cellw cellh [sx sy [colorkey [remap] ] ] ]`
> where `remap` is `callback [tile [x [y] ] ] -> [tile [flip [rotate] ] ]`
> 

Here is an example:

![ring](https://cloud.githubusercontent.com/assets/1101448/23210640/934efe42-f90f-11e6-851f-928c0e18ed60.gif)

```lua
-- title:  remap demo
-- author: nesbox
-- desc:   shows how to use map callback
-- script: lua
-- input:  gamepad

t=0
x=104
y=24

function TIC()
  cls(13)
  map(0,0,30,17,0,0,0,
    function(tile)
      return tile~=0 and tile+(2*(t%30//10))
    end)		
  t=t+1
end
```
closing on .19

**Comment by Effer** [comment]
@nesbox I like how you finally fit it. The callback with id is simple and elegant well done.

Not to stir up a hornet's nest, but isn't a paradox that TIC has a limit in RAM but not in Lua? Neither in CPU clock BTW. 
And just to be clear, I **don't** need that kind of limits.

**Comment by nesbox** [comment]
@Effer yes, here is a paradox, but I don't want to hack the Lua library and want to be able update it to newer versions without any code merging

**Comment by hseiken** [comment]
I like the idea of cpu limitation.  But I think cart ram/size limit is fine.  I'd like to see someway to keep track of active variables, maybe turn part of the RAM aspect into the ONLY place you can house values...i.e. you can name them and call them as normal in lua, but in the actual cart, you can see them (and of course, pull their values out and poke them elsewhere to see what it looks like when you take someone's status and inventory and use it to draw pixels).

**Comment by nesbox** [comment]
@hseiken for example pico8 uses tokens to limit code variables
