### ISSUE TITLE
Other Api method

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#41]
Hello,

I saw snippet function in the wiki
Have you plan for other api function like circ functions in native api in the future?

And have you got a roadmap? if yes can you share it? :-)

**Comment by nesbox** [comment]
Hi,

I don't have plans to add _circ_ function to the api because I've never needed it and no one has requested it before. If you really need it I can add 😃 

I'm going to add TIC Roadmap to the Wiki in near future.

**Comment by Gi972** [comment]
Yes I want :-)

**Comment by harraps** [comment]
you might add my 'ell' (ellipse) function too

**Comment by Raidez** [comment]
If you think to add *circ* function, just add *Andres* algo, it's the best !

**Comment by nesbox** [comment]
added new api
`circ x y radius color`
`circb x y radius color`

So, I used _Bresenham_ algorithm

![circ](https://cloud.githubusercontent.com/assets/1101448/22796440/5ef5a6c2-ef0b-11e6-8314-554115b6e7d0.gif)
The example based on [rectb](https://github.com/nesbox/tic.computer/wiki/rectb) demo written by @Effer :)
closing on .18

**Comment by nesbox** [comment]
@Raidez I used _bresenham_ because it draws the circle with 1px width border instead _andres_ which uses 2px width on some parts and it seemed strange to me
There is time before release, so let discuss if you don't like _bresenham_

![cmp](https://cloud.githubusercontent.com/assets/1101448/22800767/80d6664a-ef1b-11e6-8af6-9dc4717c56dc.gif)

**Comment by trelemar** [comment]
I like bresenham it's more consistent. Andres almost looks AA'd.

**Comment by Effer** [comment]
@nesbox that demo is having a great success :)

**Comment by nesbox** [comment]
@Effer yes, your demo is an easy way to make WOW effect :)

**Comment by Raidez** [comment]
Have you copy *circ function* I made ?
If yes, I didn't found how to fill circle on bresenham so I use andres to fill the circle.

And my perfectionism, didn't like use/cheat :)

**Comment by nesbox** [comment]
@Raidez yes, I ported your _bresenham_ algorithm to C lang
Also I used _bresenham_ to detect left and right sides of a circle and then fill it with horizontal lines

**Comment by Effer** [comment]
Probably I'm too late, but does make sense to have circ draw also ellipses? So have not only one radius but two. I'll will have the same sign as rect/rectb.

**Comment by nesbox** [comment]
@Effer don't know, no one requested ellipses, let's wait and I'll add if it really needed

**Comment by Effer** [comment]
Ok, just fund a small bug anyway. If you draw a circle with x<0
You can see there's a wrong line in the border.
![image](https://cloud.githubusercontent.com/assets/1007007/23230876/dbee9604-f945-11e6-8bbb-34a49a749c22.png)

**Comment by nesbox** [comment]
oops, I know where is an error :) pls create an issue.
Thanks
