### ISSUE TITLE
Second gamepad not processed correctly.

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#43]
I used this test program.
Clicking on the keyboard work out okay, but both of the gamepad are displayed as the first gamepad. Secondary gamepad displayed as first.
For example in the pico-8 both worked )
The operating system is Windows 7, if it is important.

```lua
--Key Test Project
--By Rain_Effect
local x=70
local y=25
local btnLabel={"Up","Down","Left","Right","Btn A","Btn B"}
function TIC()
    cls(0)
    print("Key Test Project",x,y)
 print("Btn",x,y+15,2)
    print("1P",x+50,y+15,2)
    print("2P",x+80,y+15,2)
    for i=1,6 do
     print(btnLabel[i],x,y+(i+1)*10+5)
        if btn(i-1) then
      print("On",x+50,y+(i+1)*10+5,11)
        else
      print("Off",x+47,y+(i+1)*10+5,6)
        end
        if btn(i+7) then
      print("On",x+80,y+(i+1)*10+5,11)
        else
      print("Off",x+77,y+(i+1)*10+5,6)
        end
    end
end
```

**Comment by nesbox** [comment]
Yes, only one gamepad is mapped
Will fix, thanks

**Comment by harraps** [comment]
We should be able to select the keys to map through the config.lua file, for both the keyboard and game controllers.

**Comment by nesbox** [comment]
@harraps I'm going to create a tool to configure buttons mapping #45

**Comment by nesbox** [comment]
added second controller support
please check it
[tic_gamepad_fix.zip](https://github.com/nesbox/tic.computer/files/794875/tic_gamepad_fix.zip)

_PS: SDL doesn't detect second gamepad correctly if app is already running, so connect both gamepads and only then run TIC_

closing on .19

**Comment by AlRado** [comment]
Both gamepads work fine!
