### ISSUE TITLE
Configure buttons mapping

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#45]
Make a tool to configure keyboard and gamepad buttons mapping.
Save the mapping settings in local storage.

**Comment by nesbox** [comment]
created a simple tool to configure _keyboard buttons_
use `keymap` command to run it

![keymap](https://cloud.githubusercontent.com/assets/1101448/25996630/ed09e1c8-3720-11e7-8a8e-6381edfd26e3.gif)

done in .24

**Comment by trelemar** [comment]
Very cool and useful. I really like the idea of having these small little tools you run from the console. For example you could do another one for editing the color palette in really time, and have buttons for saving the palette as system or game specific if your current game is loaded.

**Comment by jahodfra** [comment]
I quite miss keymap command. The settings is only accessible from the surf mode (and accessible only on public cartridges) so it is hard for developers to found out how to change the mapping.

**Comment by nesbox** [comment]
yes, sure
added an issue #798
