### ISSUE TITLE
VERSION command for dekstop

### ISSUE THREAD

**Issue by spazzylemons** [nesbox/tic.computer#46]
I'd find it nice to have a command for downloading a specific version of TIC from the console so I don't have to visit the itch.io site every time it is updated.
Its one parameter would be the version name/number.

**Comment by nesbox** [comment]
I don't keep all the version on the server, only latest, so I can show notification (or smth like that)  on startup when new version is available.

**Comment by spazzylemons** [comment]
My alternate idea is to add UPDATE as a command, which will automatically download the latest executable and place it in C:\Program Files or something like that.

**Comment by nesbox** [comment]
TIC doesn't have installer and it's not stored in Program Files, it's just a standalone exe.
I can try download update and replace it itself on UPDATE command.
How are you going to know that a new version is available?

**Comment by spazzylemons** [comment]
On startup, if connected to wi-fi, the exe could ping some server to check if a newer version exists. If so, it will print that on startup. As for the installer part, I suggest that the exe become "install-able" eventually.

**Comment by nesbox** [comment]
OK
about installer, why do you need it? I don't see any advantages and it's very convenient to distribute standalone binary

**Comment by spazzylemons** [comment]
It doesn't _need_ an installer, but it helps to clean up clutter by hiding the exe somewhere else, and you just pin to taskbar. I could be fine without an installer, but the check for update function would be nice.

**Comment by trelemar** [comment]
This isnt a problem on Android since the play store lets you know when updates are out, so eventually TIC could be on the windows/Ubuntu/Apple stores on desktop.

**Comment by nesbox** [comment]
@trelemar you are right, TIC is already in Windows Store https://www.microsoft.com/store/apps/9nblggh4xvfg and I have to add it to other stores, this could solve all the problems with updates (except standalone versions for win xp-7 and etc.)

**Comment by nesbox** [comment]
@spazzylemons I remembered, also you can use itch desktop application to get updates for TIC https://itch.io/app

**Comment by hseiken** [comment]
I *HATE* auto updates.  Please, if it's added outside of the already available methods, please do not auto connect to server.

**Comment by nesbox** [comment]
@hseiken autoupdate works outside TIC, you have to use itch.io app to get notified for new desktop version (win/linux/mac) or _Windows Store / Google Play_ to update mobile version

**Comment by nesbox** [comment]
autoupdate function is outside from TIC, install it from itch.io/Windows Store or Google Play to have actual version
closing

**Comment by StinkerB06** [comment]
You mean "Program Files (x86)" for 64-bit Windows because TIC is 32-bit app?
