### ISSUE TITLE
Syntax coloring for moonscript

### ISSUE THREAD

**Issue by harraps** [nesbox/tic.computer#47]
This is not important, but it would be nice to have syntax coloring for moonscript.

And since we can change the symbols for whitespace characters, those characters should be colored lightly relatively to the text.
I mean by that the background of the text editor use color 0, regular text use color 15, so whitespaces should use color 1 rather than color 15 to be darker.

**Comment by nesbox** [comment]
added syntax coloring for moonscript keywords:
```
false
true
nil
return
break
continue
for
while
if
else
unless
switch
when
and
or
in
do
not
super
try
catch
with
export
import
from
class
extends
new
```
and color for whitespace chars
![moon](https://cloud.githubusercontent.com/assets/1101448/23224051/e7744af8-f93d-11e6-99e1-ed620fe7429d.gif)

closing on .19

**Comment by harraps** [comment]
didn't you forgot the 'elseif' keyword ?

**Comment by nesbox** [comment]
yes, forgot it, thanks :)

**Comment by harraps** [comment]
Would it be possible to have special coloration for classes name and for \@  ?
Like '\@attribute' would be colored in lime green for example.

**Comment by nesbox** [comment]
@harraps it's possible, pls create a separate issue
