### ISSUE TITLE
HOTKEYS rectification

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#5]
Hi, 
Left bracket on french windows keyboard use Alt+4 , when I use Alt 4 it's change screen to go sfx editor. Can you remove this hotkey and leave only alt+F4 hotkey or fix this bug.

Thanks

**Comment by nesbox** [comment]
Hi, what if I leave left Alt as is and will only remove Alt+4 functionality for right Alt.
Will it work on french keyboard?
Thanks

**Comment by Gi972** [comment]
Yes, 
You can keep for left Alt and only remove  alt+4 functionality  for right Alt :-)  
It will be good.

**Comment by nesbox** [comment]
fixed in 0.15.0
