### ISSUE TITLE
Error occurs when i try to import GIF, OS Windows 7

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#50]
![2017-02-21_13-53-15](https://cloud.githubusercontent.com/assets/440703/23162213/1e7f8ee6-f83e-11e6-819e-f552e3236341.png)

**Comment by nesbox** [comment]
Is it reproducible with every GIF or with special?

**Comment by KochkinBochkin** [comment]
I tried to import a gif with indexed palette db16 with original size - all good

**Comment by KochkinBochkin** [comment]
sorry, not gif, but png!

**Comment by AlRado** [comment]
Here is my test image
![giftest](https://cloud.githubusercontent.com/assets/440703/23164203/0c8d1628-f847-11e6-9e22-76ebaf309cfe.gif)

**Comment by nesbox** [comment]
yes, it crashes
will fix

**Comment by trelemar** [comment]
Also, if possible, export/import for Android?

**Comment by nesbox** [comment]
@trelemar it's possible, the problem is that Android doesn't have native _file open dialog_ to open external file
On Android TIC will only save exported .gif to the working folder on `export sprites.gif` and load from the folder on 'import sprites.gif'.

**Comment by nesbox** [comment]
fixed crash on .gif import
![fixed](https://cloud.githubusercontent.com/assets/1101448/23251372/1f5a2fd4-f9be-11e6-8fe6-bc3e57f44c1f.png)
Android export/import will be fixed here #54

**Comment by nesbox** [comment]
test build
[tic_fixed_gif_import.zip](https://github.com/nesbox/tic.computer/files/800274/tic_fixed_gif_import.zip)

**Comment by AlRado** [comment]
Test build works fine!
