### ISSUE TITLE
Configuration for startup sound

### ISSUE THREAD

**Issue by harraps** [nesbox/tic.computer#51]
The sound on startup is quite loud.
It would be nice to change the volume of TIC-80 (in the config file)

And why not being able to create a custom startup sound.
So that the user can reproduce the startup sound of the gameboy or other systems.

**Comment by nesbox** [comment]
Great idea, will do something :)

**Comment by nesbox** [comment]
Added startup sound configuration, just go to SFX EDITOR, create effect and use copy/paste to save sfx data to the _config.lua_

![config](https://cloud.githubusercontent.com/assets/1101448/23505519/0797cbb2-ff55-11e6-914b-2b387bd09606.gif)

Theme configuration format:
```lua
THEME =
{
	START =
	{
		SFX="...", -- sfx data
		NOTE=42,
		VOLUME=15,
	},

	CODE =
	{
		-- also you can define code editor colors
		BG      = Color.DARK_RED,
		STRING  = Color.YELLOW,
		NUMBER  = Color.CYAN,
		KEYWORD = Color.RED,
		API     = Color.LIGHT_GREEN,
		COMMENT = Color.GRAY,
		SIGN    = Color.LIGHT_BLUE,
		VAR     = Color.WHITE,
		OTHER   = Color.BLACK,
		SELECT  = Color.DARK_GRAY,
		CURSOR  = Color.RED,
	},
}
```

closing on .20
