### ISSUE TITLE
Saving cart from the code abiliy

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#52]
This capability will save the player's progress, inventory directly in the body of the cartridge. For example in the sprites area.

**Comment by trelemar** [comment]
You want the pmem function. I don't see a need for what your saying.

**Comment by KochkinBochkin** [comment]
Okay

**Comment by nesbox** [comment]
yes, pls use `pmem` function to save progress to user local storage
and you don't have access to write to ROM area from the lua code because it's `Read Only Memory`
closing
