### ISSUE TITLE
Circ not draw correctly with x<0

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#53]
![image](https://cloud.githubusercontent.com/assets/1007007/23231236/618f7cb4-f947-11e6-8a5e-4c4cd270e5cd.png)

Here the code to reproduce it:

``` Lua
function TIC()
	cls()
	circ(-100,-100,200,8)
end
```

Circb is not affected.

**Comment by nesbox** [comment]
fixed in .19

**Comment by Effer** [comment]
Perfect. Thanks!
