### ISSUE TITLE
Export/Import on Android

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#54]
Android doesn't have native file open/save dialogs, so _export_ will just save file to TIC working folder

**Comment by nesbox** [comment]
added file load/save dialogs to Android build
therefore `export import add get` console commands work on Android now

![screenshot_2017-02-27-17-46-36](https://cloud.githubusercontent.com/assets/1101448/23365816/7fb7ab7c-fd15-11e6-8c2c-b353fe646eb7.png)
![screenshot_2017-02-27-17-46-18](https://cloud.githubusercontent.com/assets/1101448/23365817/7fbb0042-fd15-11e6-86ba-4678a9eb4b81.png)

closing on .19

**Comment by trelemar** [comment]
This is huge! Will this work for exporting html5 too or no? Awesome work.

**Comment by nesbox** [comment]
@trelemar yes, it will export html5 too

**Comment by LuccaMarinho** [comment]
I'm getting "An error occurred while viewing this webpage. To continue, tap Refresh or go to another page" when I open the .html file.

Can u help me? Using S8+
