### ISSUE TITLE
Confirmation Dialogs

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#59]
Have a simple Y/N dialogue in the console if the user tries to delete a cart, or if the user makes a new cart when the current cart has unsaved changes.

**Comment by nesbox** [comment]
I'll add confirmation text to the console:
```
> Are you sure to delete this file? [Y/N] : n
> Do you want to save chages you made? [Y/N] : n
```

**Comment by Effer** [comment]
Would be nice also on application exit.

**Comment by trelemar** [comment]
Posted this in the chat room I'll put it here though:
To go alittle bit more in detail with the dialogs, say I launch tic, then on accident I type "save game" instead of "load game"
If I already had a "game.tic" it would be overridden with the new cart.

**Comment by nesbox** [comment]
WARNING dialog shows:
- if you have unsaved changes and try to `load/new/exit` commands
- if you try to delete a file using `del` command
- if cartridge already exists and you try to overwrite it

works with mouse and keyboard

![dialogs](https://user-images.githubusercontent.com/1101448/29526304-fbc6d488-869d-11e7-9775-ebb2ec20b328.gif)

done in .31
