### ISSUE TITLE
TIC on android

### ISSUE THREAD

**Issue by lewislepton** [nesbox/tic.computer#61]
hello,

i have tried TIC on my android phone, works wonders. BUT, problem with running things is using the 'esc' key.
since this does not exist on a phone virtual keyboard it cant escape.

may need to think on another way this can be used

cheers for the great work done ;)

**Comment by nesbox** [comment]
Hi
try to use BACK button instead
Press BACK to hide screen keyboard and press second time to 'escape'
Thanks

**Comment by trelemar** [comment]
Yes, the back button works. However, I recommend using hacker's keyboard
![screenshot_20170302-100417](https://cloud.githubusercontent.com/assets/24630549/23512775/c0539d64-ff2f-11e6-8f03-466fc07adea3.png)

**Comment by lewislepton** [comment]
ah good to know about the back, also hackers keyboard
