### ISSUE TITLE
Mouse x,y,p not working in v 0.19.0

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#62]
Pressed state seems not being returned anymore. X and Y works as expected.

**Comment by nesbox** [comment]
I changed button state from `int` to `bool` in .19
```lua
x,y,b=mouse()
if b then
  spr(0,x,y,....)
end
```
and didn't announce it, my mistake, sorry

**Comment by Effer** [comment]
Better choice anyway. Thanks. Solved.
