### ISSUE TITLE
Triangle primitives

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#63]
Basically I'd like to have a way to fill some region with solid color. Actually I can do it by drawing a lot of lines, but that's seems not very performing.  
Shapes like rotated rectangles, bold lines, triangles or polygons are not so easy reproducible in TIC.
I end up on proposing a **tri** function like (x1,y1,x2,y2,x3,y3,color).
Not sure if this go out of @nesbox view of fantasy console but I'd like to see again some of that flat shading style gems of the very late 80'.

**Comment by nesbox** [comment]
ok, will add `tri(x1,y1,x2,y2,x3,y3,color)` api
thanks :)

**Comment by Effer** [comment]
Thank you!

**Comment by trelemar** [comment]
What if it was a polygon function? That allowed any number of points? Just have the minimum be 3 points.

**Comment by nesbox** [comment]
@trelemar, going to add only triangle api, don't want to complicate, sorry
you have to implement you own _polygon_ func based on _tri_

**Comment by nesbox** [comment]
added `tri x1 y1 x2 y2 x3 y3 color` api

![tri](https://cloud.githubusercontent.com/assets/1101448/23550629/245dff36-0023-11e7-98c8-267eed0c868f.gif)

demo code

```lua
local W=240 H=136 t=0

cls()

function TIC()

	if t%6==0 then
		x1=math.random()*W
		y1=math.random()*H
		x2=math.random()*W
		y2=math.random()*H
		x3=math.random()*W
		y3=math.random()*H
		c=math.random()*16
		
		tri(x1,y1,x2,y2,x3,y3,c)

	end

	t=t+1		
end
```

closing on .20
