### ISSUE TITLE
EXPORT behaves differently on Windows and HTML platforms

### ISSUE THREAD

**Issue by Kinrany** [nesbox/tic.computer#64]
On Windows 7 it creates an .html with preloaded cartridge. On HTML it creates a .gif with spritesheet.

Happens with 0.20 and .html generated by it respectively.

**Comment by trelemar** [comment]
Are you trying to get the .tic file from HTML? That's what the get command does.

**Comment by Kinrany** [comment]
Huh?

1. Run tic.exe

2. Call EXPORT

3. Save cartridge.html somewhere

4. Open cartridge.html in browser

5. Press ESC to exit to console

6. Call EXPORT again

Expected: a save file dialog with another cartridge.html

Observed: a dialog with .gif spritesheet, `sprites successfully exported :)`

**Comment by trelemar** [comment]
Do these steps, but at step 6, type "get" instead of "export". Please report back with results :)

**Comment by nesbox** [comment]
_.html game export_ works on native builds only
on _html_ version of TIC you can only export sprites, but there is a bug, it should export sprites only by calling `export sprites` command
will fix

**Comment by nesbox** [comment]
spites can be exported only by `export sprites` command
you'll get message `web version doesn't support html or native export` if you just type `export` command in web version
closing on .21
