### ISSUE TITLE
dofile on first line false detection

### ISSUE THREAD

**Issue by Effer** [nesbox/tic.computer#65]
Tic report:
![image](https://cloud.githubusercontent.com/assets/1007007/23833953/324b9126-074e-11e7-953d-cd5a7fb766de.png)

even if the dofile is on first line:
![image](https://cloud.githubusercontent.com/assets/1007007/23833959/50a98466-074e-11e7-831c-e3601140dd65.png)

Here the cartridge renamed in txt
[do.txt](https://github.com/nesbox/tic.computer/files/836655/do.txt)

**Comment by AlRado** [comment]
With double quotes work )

**Comment by Effer** [comment]
That's right. Thanks.

**Comment by trelemar** [comment]
Wait we can add external libraries this way!?

**Comment by Effer** [comment]
Don't think so. You can include just one file. It's a limit and is an exception to the single IDE rule. Thought it like a trick to allow to use an external editor. 
At the end you have to move all the code back to the Code Editor to compile correctly.

**Comment by nesbox** [comment]
will fix _dofile_ with single quotes

**Comment by nesbox** [comment]
fixed on .21
