### ISSUE TITLE
Native Scrolling on macOS

### ISSUE THREAD

**Issue by jack0088** [nesbox/tic.computer#67]
Hey, is it possible to activate "native" scrolling on mac computers? Native is inverted on y - so the you "pull" and "push" the content into the desired direction..
If not possible, could you implement it?

**Comment by nesbox** [comment]
Hmm, I fixed the scrolling issue some time ago, seems to be broken again, will fix.
Thanks.

**Comment by nesbox** [comment]
fixed
closing on .21

**Comment by unstoppablecarl** [comment]
not everyone using osx likes this setting and has it on. Is there a way to make this optional?

**Comment by nesbox** [comment]
@unstoppablecarl sorry, you want to disable scrolling or what?
