### ISSUE TITLE
Cursor Jump

### ISSUE THREAD

**Issue by jack0088** [nesbox/tic.computer#68]
Is it possible to use CMD + arrow keys to jump to line end or line start
or ALT + arrow keys to jump by words?

Its kinda tedious to move the cursor character by character...

**Comment by trelemar** [comment]
Try home and end keys.

**Comment by nesbox** [comment]
ok, I'll add:
- CMD+arrows to jump start/end
- ALT/CTRL+arrows to jump by words

Thanks

**Comment by nesbox** [comment]
fixed on .21
