### ISSUE TITLE
Add the ability to run the tic application from the command line with the following parameters: -cart game.tic, -code code.lua 

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#69]
For example:
tic -cart game.tic 
tic -code code.lua

**Comment by nesbox** [comment]
will do
`tic -cart game.tic -code code.lua` means open cartridge `game.tic` and inject `code.lua` to it and run

**Comment by nesbox** [comment]
`> tic game.tic` - load cartridge and run game
`> tic -code game.lua` - load and run the code without startup animation
`> tic game.tic -code game.lua` - load cartridge, inject the code and run without startup animation

closing on .21
