### ISSUE TITLE
A suggest: Setting button in code

### ISSUE THREAD

**Issue by RainEffect** [nesbox/tic.computer#7]
Now the keys are not easy to click. [Only 2P> btn(8..13)]
Can make a command to set up button?
E.g: setBtn(id, key)

**Comment by nesbox** [comment]
the game API has access only to gamepad buttons to avoid problems with input on mobile devices for example, but I'm going to add TIC config tool where you can setup your personal local key bindings

**Comment by RainEffect** [comment]
Thanks
