### ISSUE TITLE
Panning map editor on Android

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#73]
I know @nesbox is aware of this issue but it is currently impossible to pan the map editor viewport on Android. This means you cannot edit the top row at all. Any solution would be greatly appreciated at this point!

**Comment by nesbox** [comment]
You can select edit area by dragging red rectangle
![7c0e91ac-3000-11e7-8fd4-6db847855472](https://cloud.githubusercontent.com/assets/1101448/26443033/7e06bcc8-413f-11e7-94f6-155a4a16db57.gif)
closing on .25
