### ISSUE TITLE
Breakpoints / pause

### ISSUE THREAD

**Issue by ke-si** [nesbox/tic.computer#77]
Can you **please** add a `breakpoint()` _(`pause()`)_ function? **Thanks**.

**Comment by nesbox** [comment]
What should happen when breakpoint/pause occurred?

**Comment by ke-si** [comment]
It should pause the `update()` function and wait until a certain key is pressed. (`<ENTER>`)

**Comment by trelemar** [comment]
If your adding a dedicated pause function a start button would be appreciated!

**Comment by Effer** [comment]
Well... what if you add a break point in the editor? with a watch window? That's will make TIC80 a step over.(and will put in serious risk my social life..)

**Comment by harraps** [comment]
Is there really a need for pause when you just need to create a global variable 'PAUSE' and test if it is set to 'true' or 'false' at the root of the 'update' function ?

**Comment by nesbox** [comment]
@harraps great idea, I really don't want to overload TIC with the new api methods

**Comment by hseiken** [comment]
I think this is true for several recent requests.  I hope that similar approaches to their legitimacy and/or necessity are considered (specifically adding 'scale' to everything and anything...consider get(corner, corner)/put(point, scale, transparent color{s}) for instance which could grab graphic buffer at any time and scale it and move it, more like a blitter for instance)

Just ideas and agreeing with this implmentation of the request and more like it.  LUA's already ridiculously capable.  I feel like some of these requests could be added by the user themselves with a default file and some clever global variables.

**Comment by trelemar** [comment]
I agree with @hseiken and @nesbox. The user can pretty easily make their own pause function. With a generic API method, it would freeze what's currently being drawn, but if you make your own, you could display anything you wanted when the game is paused.

**Comment by nesbox** [comment]
closing...
