### ISSUE TITLE
Scaling the text with print() function

### ISSUE THREAD

**Issue by ke-si** [nesbox/tic.computer#78]
Can you **please** add a text scaling for the `print()` function? **Thanks**.

**Comment by nesbox** [comment]
added _scale_ param to `print` and `font` api
`print text [ x y [ color [ fixed [ scale ] ] ] ] -> width`
`font text [ x y [ color [ fixed [ scale ] ] ] ] -> width`

![image](https://cloud.githubusercontent.com/assets/1101448/25661716/5bccef00-301a-11e7-8531-e9997a9b354b.png)

close on .23
