### ISSUE TITLE
Improvement the "world map" in the "map editor"

### ISSUE THREAD

**Issue by AlRado** [nesbox/tic.computer#79]
It seems to me possible to make the display of cells / screens in the world map better.
Attached a picture of the current display and my sketch.

Current "world map":
![tilemapcurrent](https://cloud.githubusercontent.com/assets/440703/24505185/ab042de6-1561-11e7-9819-bd8c492b96e1.png)

My sketch:
![tilemapsketch](https://cloud.githubusercontent.com/assets/440703/24505225/cc8ef0e0-1561-11e7-87d0-6607a0da8768.png)

**Comment by nesbox** [comment]
I left _world map_ grid 1px width, but added right-bottom border.
You can select edit area by dragging _red_ rectangle and use TAB button to switch world/map mode
![map](https://cloud.githubusercontent.com/assets/1101448/25656194/7c0e91ac-3000-11e7-8fd4-6db847855472.gif)

closing on .23
