### ISSUE TITLE
Cart data layout documentation

### ISSUE THREAD

**Issue by UninspiredUsername** [nesbox/tic.computer#80]
Is the cart data layout set in stone at this point? If so, can we get some documentation on it? Not that it'd be super useful since there's currently no functions that make use of cart data directly as far as I know.

There should also be a CART or ROM command to show the layout (similar to the RAM command) assuming it's not just literally the same as it is for ram byte for byte. (Which would be weird considering a large chunk of the ram is the screen, something that'd have no use being included in the cart data)

**Comment by nesbox** [comment]
only RAM data layout is more less stable
TIC-80 is developing and ROM/CART layouts are often changing, I'm going to create documentation closer to stable 1.0.0 version
for now CART format is
```
1 byte - chunk type (tiles-1, sprites-2, cover-3, map-4, code-5, sound-6, music-7)
3 bytes - chunk size
chunk data
...
```

**Comment by nesbox** [comment]
preparing to publish **80K RAM** layout documentation
it's approximately how it will look in 0.28.0
```
+-------------------------------------+
|            80K RAM LAYOUT           |
+-------+---------------------+-------+
| ADDR  | INFO                | SIZE  |
+-------+---------------------+-------+
| 00000 | SCREEN              | 16320 |
| 03FC0 | PALETTE             | 48    |
| 03FF0 | PALETTE MAP         | 8     |
| 03FF8 | BORDER COLOR        | 1     |
| 03FF9 | SCREEN OFFSET       | 2     |
| 03FFB | MOUSE CURSOR SPRITE | 1     |
| 03FFC | ...                 | 4     |
| 04000 | SPRITES             | 16384 |
| 08000 | MAP                 | 32640 |
| 0FF80 | SOUND REGISTERS     | 72    |
| 0FFC8 | PERSISTENT MEMORY   | 56    |
| 10000 | WAVEFORMS           | 256   |
| 10100 | SFX                 | 4224  |
| 11180 | MUSIC PATTERNS      | 6144  |
| 12980 | MUSIC TRACKS        | 280   |
| 12A98 | ...                 | 5480  |
| 13FFF | last byte           |       |
+-------+---------------------+-------+
```

**Comment by trelemar** [comment]
https://github.com/nesbox/tic.computer/wiki#specification

**Comment by nesbox** [comment]
closing...
