### ISSUE TITLE
trim api func

### ISSUE THREAD

**Issue by nesbox** [nesbox/tic.computer#81]
`trim(x,y,with,height)` - limits drawing area to _x,y,width,height_.
Called with no arguments `trim()` - allow drawing everywhere on screen.
from:https://itch.io/t/71209/ui-library-ticuare-and-request-for-trim-function

**Comment by trelemar** [comment]
I like the idea, but maybe name it crop instead of trim?

**Comment by nesbox** [comment]
or `clip`

**Comment by trelemar** [comment]
I guess It doesn't matter much. So if I understand:
```lua
trim(52,0,136,136)
print("Hello!",0,0)
```
52 would become the new x origin of all draw functions?

**Comment by Crutiatix** [comment]
I have this idea about how it should work: 
**code:**
```lua
cls(1)
trim(30,30,160,50)
spr(1,10,10,-1,8)
trim()
spr(1,100,50,-1,8)

```
**result:** (yellow rectb is only for infomation where _trim_ is placed.)
![trim](https://cloud.githubusercontent.com/assets/17261132/24754605/77606a88-1ad7-11e7-9d6b-26b55328ead5.jpg)

**Comment by Effer** [comment]
I vote for *clip*. Trim remind me of string.

**Comment by hseiken** [comment]
I think clip is just fine.  I just have a question about performance...

If you draw a scene into a clip region and the scene extends outside of the clip, is the scene still internally fully drawn and take full cpu power to draw all of the scene ouside of clip region?  I only ask because it would useful to know in terms of setting up screen realestate and maintaining steady speeds of screen refresh.

**Comment by nesbox** [comment]
I don't know when .22 will be released, working with Music Editor now, 
so I made a quick build with `clip` api to test
use `clip(x,y,w,h)` to set or `clip()` to reset
[tic_with_clip_api.zip](https://github.com/nesbox/tic.computer/files/904706/tic_with_clip_api.zip)
@Crutiatix

**Comment by nesbox** [comment]
@hseiken yes, scene is internally fully drawn outside of the clip in the current version. I'm developing TIC without any performance optimization now, as is, of course going to fix it when api will be more less stable

**Comment by Crutiatix** [comment]
@nesbox Thanks! I didn't expect it so soon! Works like a charm. Good work!

**Comment by trelemar** [comment]
I'd love to see this in the next version :)

**Comment by nesbox** [comment]
it's already in .22 :)
closing

**Comment by trelemar** [comment]
Oh wow I didn't even notice, it wasn't on the change log last time I looked. Awesome!

**Comment by nesbox** [comment]
@trelemar forgot to add it :)
