### ISSUE TITLE
Add "cd" command for the console

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#82]
Change directory command, would require folders to be visible and accessible.
Would make it easier to sort your cartridges.

**Comment by nesbox** [comment]
also will add `mkdir` command

**Comment by nesbox** [comment]
![dir](https://cloud.githubusercontent.com/assets/1101448/25962974/68b7457a-3688-11e7-93fc-884f3b7edcdf.gif)

done in .24
