### ISSUE TITLE
Print type of object

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#84]
Hello,

It's possible in the print function  return the type of object?

exemple when I make 

```lua
local a={}
local b=true
local c = 12
print(a,0,10)
print(b,0,20)
print(c,0,30)
```

should display

```
Table
true
12
```

Except if you a tip for return type with the print function.

thanks

**Comment by Crutiatix** [comment]
I'm not sure if I understand your problem, but lua has in its standard library function **type()** which return string containing type of object.
```lua
local a={}
local b = true
local c = 12
print(type(a),0,10)   -- prints "table"
print(type(b),0,10)  -- prints "boolean"
print(type(c),0,10)  -- prints "number"
```

**Comment by AnastasiaDunbar** [comment]
There's also the `tostring(object)` function.

**Comment by Gi972** [comment]
Thanks,

The method tostring is most near what I look for.

**Comment by nesbox** [comment]
closing then
