### ISSUE TITLE
Add the ability to export/import the game code so it can be edited externally

### ISSUE THREAD

**Issue by drako0812** [nesbox/tic.computer#85]
You could probably print a message if the imported code is too large, and in that case don't overwrite the current code.

Also, you could probably name the file `<cart-name>.lua` for simplicity, except that doesn't cover the case of an unsaved new cart.

**Comment by nesbox** [comment]
There are two methods to edit code in external editor:
- add `dofile('game.lua')` to the first line and place `game.lua` near TIC exe
- or use `tic cart.tic -code game.lua` command line parameters to inject your code to the cartridge (https://github.com/nesbox/tic.computer/wiki#command-line-arguments)

**Comment by nesbox** [comment]
pls close the issue if this helped you
thanks

**Comment by drako0812** [comment]
Oh right, thanks! I remember reading about those, I was tired when I opened the issue.
