### ISSUE TITLE
The "mset" function affects the map in the map editor

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#86]
Is there a way to prevent this?

**Comment by nesbox** [comment]
yes, `mset` affects the map in the editor, it can be useful if you want to make procgen map or store any data to the cart, to prevent it you have to not call 'mset' at all and use `remap` callback parameter https://github.com/nesbox/tic.computer/wiki/map

I see the following workaround:
- store all the map data to Lua table
- in `remap` callback return new tile ID from the Lua table

here is small example https://tic.computer/play?cart=9 where I change tiles on map rendering stage
So, hope this will help you, if yes pls close the issue.

Thanks

**Comment by AnastasiaDunbar** [comment]
Cool but I have code that looks kind of like this:
```lua
--My player object
player={x=0,y=0}
--Search for player in the map
for y=0,height do
 for x=0,width do
  if(mget(x,y)==playerID)then
   --Remove the player from the map and set position
   mset(x,y,0)
   player.x=x
   player.y=y
  end
 end
end
function TIC()
 --[[
  Code for player movements etc.
 --]]
 map(0,0,width,height)
 spr(playerID,player.x,player.y)
end
```

**Comment by nesbox** [comment]
ok, in this case don't remove player from the map and use _remap_ to not draw the player
``` lua
function TIC()
 --[[
  Code for player movements etc.
 --]]
 map(0,0,width,height,0,0,0,function(id)return id==playerID and 0 or id end)
 spr(playerID,player.x,player.y)
end

```
