### ISSUE TITLE
"sfx(-1)" is required before playing same sound, duration parameter to sfx api.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#87]
Even have to use `sfx(-1)` as an initializer.
Also using a value greater than 4 (or less than 0) for sfx channel then the application will crash.

**Comment by nesbox** [comment]
will fix and try to make `sfx` easier
thanks

**Comment by trelemar** [comment]
I'm gonna merge the other issue from here as there very similar and both relate:
https://github.com/nesbox/tic.computer/issues/98

**Comment by nesbox** [comment]
you don't need to call `sfx(-1)` to stop playing sfx before start a new, it fixed since .22

- but app still crashes if channel less than 0 or greater than 3
- also I'm going to add _duration_ parameter

**Comment by nesbox** [comment]
added _duration_ parameter
`sfx [id [ note [ duration [ channel [ volume [ speed ] ] ] ] ] ]`
_note_ - is absolute note = `octave * 12 + note`
_duration_ - how many ticks to play sfx = -1 by default, to play sfx infinitely

done on .23
