### ISSUE TITLE
mouse scroll

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#9]
Hello,

I don't know if I'm alone, but I have a problem with the trackpad scroll on my mac.
The scroll down only and doesn't up. 

But it is not blocking, it's just a little bug.

**Comment by nesbox** [comment]
Hi,

On MacOSX Sierra all is working fine, but I used virtual machine to test it.
What OS you're using?

**Comment by Gi972** [comment]
Hello,

My version is MacOs sierra 10.12.2
We should wait for further notice.

For android , I test editor, I can only put the text Highlighting when i try scroll. Have you a plan to scroll? maybe put two arrows  at the right of editor, one for up, one for down. It just a suggestion

**Comment by nesbox** [comment]
Going to add custom keyboard for mobile versions of TIC with navi arrows and etc.
Also I'm planning to make scroll by double tap and drag.

**Comment by Gi972** [comment]
<img width="1033" alt="tic" src="https://cloud.githubusercontent.com/assets/1606247/22166913/d50d4e76-df63-11e6-87cb-2aff881edb9e.png">


Good milestones.

Ok to help you like you have a virtual machine, I make a screenshot. Buttons appears when I move the cursor on the tic screen.  It's a normal behavior?  the buttons disappears after few seconds when I touch the keyboard.

**Comment by nesbox** [comment]
It's not a normal behavior
I made a build for you, could you pls test it
https://1drv.ms/u/s!AlYcILUh3RFajMFMmTKyTRyio-RwQA

**Comment by Gi972** [comment]
Ok,
I Test it , it works I don't see buttons anymore.

However the scrolling problem is always present.
I make a test with a connected usb mouse too but I have the same problem, the scrolling in editor  down only not up.

**Comment by nesbox** [comment]
Pls try the version with fixed scrolling
https://1drv.ms/u/s!AlYcILUh3RFajMFNWAHzF723Vw8A6A

**Comment by Gi972** [comment]
Hi,

I try, It works!!! congratulations, good job! :-)

you can close this issue ;-)

**Comment by nesbox** [comment]
done
