### ISSUE TITLE
Cover image palette changed

### ISSUE THREAD

**Issue by AnastasiaDunbar** [nesbox/tic.computer#93]
Was playing around with the palette in config and I realized that the colors have been changed for TIC-80 PAINT.
![image](https://cloud.githubusercontent.com/assets/11806048/24826811/e56fa62a-1c70-11e7-8350-f2bf1e0d9be7.png)
This is the original:
![image](https://cloud.githubusercontent.com/assets/11806048/24826830/5a5a037c-1c71-11e7-9f30-7928d29d162c.png)

**Comment by nesbox** [comment]
tried to reproduce but without success
any tips?

**Comment by nesbox** [comment]
made a fix
test build for @AlRado [tic.zip](https://github.com/nesbox/tic.computer/files/1035359/tic.zip)
