### ISSUE TITLE
back on the precedent screen

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#96]
Hello,

When I'm on the editor and I run the code with Ctrl+R for test and I Back whit  ESC button it's possible to return directly on the editor instead of console?

Thanks

**Comment by Crutiatix** [comment]
It's possible to return directly to the code editor from a running program if you press F1 instead of ESC. (or F2, F3, F4... for others editors)

**Comment by nesbox** [comment]
Or press ESC twice

**Comment by Gi972** [comment]
Ok I did not think F1 button good idea. 

I close
